### Get Clockify workspaces
GET https://api.clockify.me/api/workspaces/
Accept: application/json
X-Api-Key: {{clockify-api-key}}

### Get Clockify workspace users for workspace
GET https://api.clockify.me/api/workspaces/{{clockify-workspace-id}}/users/
Accept: application/json
X-Api-Key: {{clockify-api-key}}

### Get Clockify time entries for workspace for user in 2018
POST https://api.clockify.me/api/workspaces/{{clockify-workspace-id}}/timeEntries/user/{{clockify-user-id}}/entriesInRange
Accept: application/json
Content-Type: application/json
X-Api-Key: {{clockify-api-key}}

{
  "start": "2018-01-01T00:00:00.020Z",
  "end": "2018-12-31T23:59:59.020Z"
}
###

### Get Clockify projects
GET https://api.clockify.me/api/workspaces/{{clockify-workspace-id}}/projects/
Accept: application/json
X-Api-Key: {{clockify-api-key}}

### Generate Clockify summary report
POST https://api.clockify.me/api/workspaces/{{clockify-workspace-id}}/reports/summary/
Accept: application/json
Content-Type: application/json
X-Api-Key: {{clockify-api-key}}

{
  "startDate": "2018-01-01T00:00:00.020Z",
  "endDate": "2018-12-31T23:59:59.020Z",
  "me": "true",
  "userGroupIds": [],
  "userIds": [],
  "projectIds": [],
  "clientIds": [],
  "taskIds": [],
  "tagIds": [],
  "billable": "BOTH",
  "includeTimeEntries": "true",
  "zoomLevel": "week",
  "description": "",
  "archived": "All",
  "roundingOn": "false"
}
###

### Get Clockify reports
GET https://api.clockify.me/api/workspaces/{{clockify-workspace-id}}/reports/
Accept: application/json
X-Api-Key: {{clockify-api-key}}

###
