### Get Toggl workspaces
GET https://www.toggl.com/api/v8/workspaces
Accept: application/json
Authorization: Basic {{toggl-auth}}

### Get Toggl workspace users for personal workspace
GET https://www.toggl.com/api/v8/workspaces/{{toggl-workspace-id-personal}}/users
Accept: application/json
Authorization: Basic {{toggl-auth}}

### Get Toggl workspace users for work workspace
GET https://www.toggl.com/api/v8/workspaces/{{toggl-workspace-id-work}}/users
Accept: application/json
Authorization: Basic {{toggl-auth}}

### Get Toggl time entries for personal workspace
// https://toggl.com/reports/api/v2/details?workspace_id=123&since=2013-05-19&until=2013-05-20&user_agent=api_test

GET https://www.toggl.com/reports/api/v2/details?workspace_id={{toggl-workspace-id-personal}}&since=2017-01-01&until=2017-12-31&user_agent={{toggl-email}}
Accept: application/json
Authorization: Basic {{toggl-auth}}

###
