/* eslint-disable */
import type { ReduxState } from "~/types";
import {
  EntityGroup,
  FetchStatus,
  ToolAction,
  ToolName,
  type Client,
  type Credentials,
  type Project,
  type Tag,
  type Task,
  type TimeEntry,
  type User,
  type UserGroup,
  type Workspace,
} from "~/types";

const CLOCKIFY_CLIENT_ID_FAKE = "clock-client-01";
const CLOCKIFY_PROJECT_ID_FAKE = "clock-project-01";
const CLOCKIFY_TAG_ID_FAKE = "clock-tag-01";
const CLOCKIFY_TASK_ID_FAKE = "clock-task-01";
const CLOCKIFY_TIME_ENTRY_ID_FAKE = "clock-entry-01";
const CLOCKIFY_USER_ID_FAKE = "clock-user-01";
const CLOCKIFY_USER_GROUP_ID_FAKE = "clock-user-group-01";
const CLOCKIFY_WORKSPACE_ID_FAKE = "clock-workspace-01";

const TOGGL_CLIENT_ID_FAKE = "3001";
const TOGGL_PROJECT_ID_FAKE = "2001";
const TOGGL_TAG_ID_FAKE = "4001";
const TOGGL_TASK_ID_FAKE = "7001";
const TOGGL_TIME_ENTRY_ID_FAKE = "8001";
const TOGGL_USER_ID_FAKE = "6001";
const TOGGL_USER_GROUP_ID_FAKE = "5001";
const TOGGL_WORKSPACE_ID_FAKE = "1001";

const CLOCKIFY_WORKSPACE_FAKE: Workspace = {
  id: CLOCKIFY_WORKSPACE_ID_FAKE,
  name: "Test Workspace",
  userIds: [],
  isAdmin: true,
  isPaid: false,
  workspaceId: CLOCKIFY_WORKSPACE_ID_FAKE,
  entryCount: 0,
  linkedId: TOGGL_WORKSPACE_ID_FAKE,
  isIncluded: true,
  memberOf: EntityGroup.Workspaces,
};

const CLOCKIFY_CLIENT_FAKE: Client = {
  id: CLOCKIFY_CLIENT_ID_FAKE,
  name: "Test Client A",
  workspaceId: CLOCKIFY_WORKSPACE_ID_FAKE,
  entryCount: 0,
  linkedId: TOGGL_CLIENT_ID_FAKE,
  isIncluded: false,
  memberOf: EntityGroup.Clients,
};

const CLOCKIFY_CREDENTIALS_FAKE: Credentials = {
  apiKey: "CLOCKIFYAPIKEY",
  email: "test-user@test.com",
  userId: CLOCKIFY_USER_ID_FAKE,
};

const CLOCKIFY_PROJECT_FAKE: Project = {
  id: CLOCKIFY_PROJECT_ID_FAKE,
  name: "Test Project A",
  workspaceId: CLOCKIFY_WORKSPACE_ID_FAKE,
  clientId: CLOCKIFY_CLIENT_ID_FAKE,
  isBillable: false,
  isPublic: false,
  isActive: true,
  color: "#ea468d",
  estimate: {
    estimate: "PT0S",
    type: "AUTO",
  } as const,
  userIds: [CLOCKIFY_USER_ID_FAKE],
  entryCount: 0,
  linkedId: TOGGL_PROJECT_ID_FAKE,
  isIncluded: false,
  memberOf: EntityGroup.Projects,
};

const CLOCKIFY_TAG_FAKE: Tag = {
  id: CLOCKIFY_TAG_ID_FAKE,
  name: "tag-a",
  workspaceId: CLOCKIFY_WORKSPACE_ID_FAKE,
  entryCount: 0,
  linkedId: TOGGL_TAG_ID_FAKE,
  isIncluded: false,
  memberOf: EntityGroup.Tags,
};

const CLOCKIFY_TASK_FAKE: Task = {
  id: CLOCKIFY_TASK_ID_FAKE,
  name: "Task 1",
  estimate: "PT1H30M15S",
  projectId: CLOCKIFY_PROJECT_ID_FAKE,
  assigneeIds: [CLOCKIFY_USER_ID_FAKE],
  isActive: true,
  workspaceId: CLOCKIFY_WORKSPACE_ID_FAKE,
  entryCount: 0,
  linkedId: TOGGL_TASK_ID_FAKE,
  isIncluded: false,
  memberOf: EntityGroup.Tasks,
};

const CLOCKIFY_TIME_ENTRY_FAKE: TimeEntry = {
  id: CLOCKIFY_TIME_ENTRY_ID_FAKE,
  description: "This is a test entry (01)",
  isBillable: false,
  start: new Date("2019-06-25T18:00:00.000Z"),
  end: new Date("2019-06-25T23:00:00.000Z"),
  year: 2019,
  isActive: false,
  clientId: CLOCKIFY_CLIENT_ID_FAKE,
  projectId: CLOCKIFY_PROJECT_ID_FAKE,
  tagIds: [CLOCKIFY_TAG_ID_FAKE, "clock-tag-02"],
  tagNames: [CLOCKIFY_TAG_FAKE.name, "tag-b"],
  taskId: CLOCKIFY_TASK_ID_FAKE,
  userId: CLOCKIFY_USER_ID_FAKE,
  userGroupIds: [],
  workspaceId: CLOCKIFY_WORKSPACE_ID_FAKE,
  entryCount: 0,
  linkedId: TOGGL_TIME_ENTRY_ID_FAKE,
  isIncluded: true,
  memberOf: EntityGroup.TimeEntries,
};

const CLOCKIFY_USER_FAKE: User = {
  id: CLOCKIFY_USER_ID_FAKE,
  name: "John Test",
  email: "test-user@test.com",
  isAdmin: null,
  isActive: true,
  userGroupIds: [],
  workspaceId: CLOCKIFY_WORKSPACE_ID_FAKE,
  entryCount: 0,
  linkedId: TOGGL_USER_ID_FAKE,
  isIncluded: false,
  memberOf: EntityGroup.Users,
};

const CLOCKIFY_USER_GROUP_FAKE: UserGroup = {
  id: CLOCKIFY_USER_GROUP_ID_FAKE,
  name: "Admins",
  userIds: [CLOCKIFY_USER_ID_FAKE],
  workspaceId: CLOCKIFY_WORKSPACE_ID_FAKE,
  entryCount: 0,
  linkedId: null,
  isIncluded: true,
  memberOf: EntityGroup.UserGroups,
};

const TOGGL_WORKSPACE_FAKE: Workspace = {
  id: TOGGL_WORKSPACE_ID_FAKE,
  name: "Test Workspace",
  userIds: [TOGGL_USER_ID_FAKE],
  isAdmin: true,
  isPaid: false,
  workspaceId: TOGGL_WORKSPACE_ID_FAKE,
  entryCount: 20,
  linkedId: CLOCKIFY_WORKSPACE_ID_FAKE,
  isIncluded: true,
  memberOf: EntityGroup.Workspaces,
};

const TOGGL_CLIENT_FAKE: Client = {
  id: TOGGL_CLIENT_ID_FAKE,
  name: "Test Client A",
  workspaceId: TOGGL_WORKSPACE_ID_FAKE,
  entryCount: 3,
  linkedId: CLOCKIFY_CLIENT_ID_FAKE,
  isIncluded: false,
  memberOf: EntityGroup.Clients,
};

const TOGGL_CREDENTIALS_FAKE: Credentials = {
  apiKey: "TOGGLAPIKEY",
  email: "test-user@test.com",
  userId: TOGGL_USER_ID_FAKE,
};

const TOGGL_PROJECT_FAKE: Project = {
  id: TOGGL_PROJECT_ID_FAKE,
  name: "Test Project A",
  workspaceId: TOGGL_WORKSPACE_ID_FAKE,
  clientId: TOGGL_CLIENT_ID_FAKE,
  isBillable: false,
  isPublic: false,
  isActive: true,
  color: "#ea468d",
  estimate: {
    estimate: 0,
    type: "MANUAL",
  } as const,
  userIds: [TOGGL_USER_ID_FAKE],
  entryCount: 3,
  linkedId: CLOCKIFY_PROJECT_ID_FAKE,
  isIncluded: false,
  memberOf: EntityGroup.Projects,
};

const TOGGL_TAG_FAKE: Tag = {
  id: TOGGL_TAG_ID_FAKE,
  name: "tag-a",
  workspaceId: TOGGL_WORKSPACE_ID_FAKE,
  entryCount: 1,
  linkedId: CLOCKIFY_TAG_ID_FAKE,
  isIncluded: false,
  memberOf: EntityGroup.Tags,
};

const TOGGL_TASK_FAKE: Task = {
  id: TOGGL_TASK_ID_FAKE,
  name: "Task 1",
  estimate: "PT2H",
  projectId: TOGGL_PROJECT_ID_FAKE,
  assigneeIds: ["123123"],
  isActive: true,
  workspaceId: TOGGL_WORKSPACE_ID_FAKE,
  entryCount: 2,
  linkedId: CLOCKIFY_TASK_ID_FAKE,
  isIncluded: false,
  memberOf: EntityGroup.Tasks,
};

const TOGGL_TIME_ENTRY_FAKE: TimeEntry = {
  id: TOGGL_TIME_ENTRY_ID_FAKE,
  description: "This is a test entry (01)",
  isBillable: false,
  start: new Date("2019-06-25T18:00:00.000Z"),
  end: new Date("2019-06-25T23:00:00.000Z"),
  year: 2019,
  isActive: false,
  clientId: TOGGL_CLIENT_ID_FAKE,
  projectId: TOGGL_PROJECT_ID_FAKE,
  tagIds: [TOGGL_TAG_ID_FAKE, "4002"],
  tagNames: [TOGGL_TAG_FAKE.name, "tag-b"],
  taskId: TOGGL_TASK_ID_FAKE,
  userId: TOGGL_USER_ID_FAKE,
  userGroupIds: [],
  workspaceId: TOGGL_WORKSPACE_ID_FAKE,
  entryCount: 0,
  linkedId: CLOCKIFY_TIME_ENTRY_ID_FAKE,
  isIncluded: false,
  memberOf: EntityGroup.TimeEntries,
};

const TOGGL_USER_FAKE: User = {
  id: TOGGL_USER_ID_FAKE,
  name: "John Test",
  email: "test-user@test.com",
  isAdmin: null,
  isActive: true,
  userGroupIds: [],
  workspaceId: TOGGL_WORKSPACE_ID_FAKE,
  entryCount: 0,
  linkedId: CLOCKIFY_USER_ID_FAKE,
  isIncluded: false,
  memberOf: EntityGroup.Users,
};

const TOGGL_USER_GROUP_FAKE: UserGroup = {
  id: TOGGL_USER_GROUP_ID_FAKE,
  name: "Test Group A",
  userIds: [],
  workspaceId: TOGGL_WORKSPACE_ID_FAKE,
  entryCount: 0,
  linkedId: CLOCKIFY_USER_GROUP_ID_FAKE,
  isIncluded: false,
  memberOf: EntityGroup.UserGroups,
};

const REDUX_STATE_FAKE: ReduxState = {
  allEntities: {
    areExistsInTargetShown: true,
    entityGroupInProcess: null,
    fetchAllFetchStatus: FetchStatus.Pending,
    pushAllChangesFetchStatus: FetchStatus.Pending,
    toolAction: ToolAction.Transfer,
    toolNameByMapping: {
      source: ToolName.Toggl,
      target: ToolName.Clockify,
    },
    transferCountsByEntityGroup: {
      clients: 0,
      tags: 0,
      projects: 0,
      tasks: 0,
      timeEntries: 0,
      users: 0,
      userGroups: 0,
    },
  },
  app: {
    notifications: [],
  },
  credentials: {
    source: {
      ...TOGGL_CREDENTIALS_FAKE,
    },
    target: {
      ...CLOCKIFY_CREDENTIALS_FAKE,
    },
    validationErrorsByMapping: {
      source: "Error getting source",
      target: "Error getting target",
    },
    validationFetchStatus: FetchStatus.Pending,
  },
  clients: {
    source: {
      [TOGGL_CLIENT_ID_FAKE]: {
        ...TOGGL_CLIENT_FAKE,
      },
      "3002": {
        id: "3002",
        name: "Test Client B",
        workspaceId: TOGGL_WORKSPACE_ID_FAKE,
        entryCount: 3,
        linkedId: "clock-client-02",
        isIncluded: false,
        memberOf: EntityGroup.Clients,
      },
    },
    target: {
      [CLOCKIFY_CLIENT_ID_FAKE]: {
        ...CLOCKIFY_CLIENT_FAKE,
      },
      "clock-client-02": {
        id: "clock-client-02",
        name: "Test Client B",
        workspaceId: CLOCKIFY_WORKSPACE_ID_FAKE,
        entryCount: 0,
        linkedId: "3002",
        isIncluded: false,
        memberOf: EntityGroup.Clients,
      },
    },
    isFetching: false,
  },
  projects: {
    source: {
      [TOGGL_PROJECT_ID_FAKE]: {
        ...TOGGL_PROJECT_FAKE,
      },
      "2002": {
        id: "2002",
        name: "Test Project B",
        workspaceId: TOGGL_WORKSPACE_ID_FAKE,
        clientId: null,
        isBillable: false,
        isPublic: false,
        isActive: false,
        color: "#3750b5",
        estimate: {
          estimate: 40,
          type: "MANUAL",
        },
        userIds: [TOGGL_USER_ID_FAKE],
        entryCount: 3,
        linkedId: "clock-project-02",
        isIncluded: false,
        memberOf: EntityGroup.Projects,
      },
      "2003": {
        id: "2003",
        name: "Test Project C",
        workspaceId: TOGGL_WORKSPACE_ID_FAKE,
        clientId: null,
        isBillable: false,
        isPublic: false,
        isActive: true,
        color: "#c56bff",
        estimate: {
          estimate: 0,
          type: "MANUAL",
        },
        userIds: [TOGGL_USER_ID_FAKE],
        entryCount: 3,
        linkedId: "clock-project-03",
        isIncluded: false,
        memberOf: EntityGroup.Projects,
      },
      "2004": {
        id: "2004",
        name: "Test Project D",
        workspaceId: TOGGL_WORKSPACE_ID_FAKE,
        clientId: null,
        isBillable: false,
        isPublic: false,
        isActive: true,
        color: "#04bb9b",
        estimate: {
          estimate: 0,
          type: "MANUAL",
        },
        userIds: [TOGGL_USER_ID_FAKE],
        entryCount: 3,
        linkedId: null,
        isIncluded: true,
        memberOf: EntityGroup.Projects,
      },
      "2005": {
        id: "2005",
        name: "Test Project E",
        workspaceId: TOGGL_WORKSPACE_ID_FAKE,
        clientId: null,
        isBillable: false,
        isPublic: false,
        isActive: true,
        color: "#205500",
        estimate: {
          estimate: 0,
          type: "MANUAL",
        },
        userIds: [TOGGL_USER_ID_FAKE],
        entryCount: 4,
        linkedId: null,
        isIncluded: true,
        memberOf: EntityGroup.Projects,
      },
      "2006": {
        id: "2006",
        name: "Test Project F",
        workspaceId: TOGGL_WORKSPACE_ID_FAKE,
        clientId: null,
        isBillable: false,
        isPublic: false,
        isActive: true,
        color: "#a01aa5",
        estimate: {
          estimate: 0,
          type: "MANUAL",
        },
        userIds: [TOGGL_USER_ID_FAKE],
        entryCount: 4,
        linkedId: null,
        isIncluded: false,
        memberOf: EntityGroup.Projects,
      },
    },
    target: {
      [CLOCKIFY_PROJECT_ID_FAKE]: {
        ...CLOCKIFY_PROJECT_FAKE,
      },
      "clock-project-02": {
        id: "clock-project-02",
        name: "Test Project B",
        workspaceId: CLOCKIFY_WORKSPACE_ID_FAKE,
        clientId: "clock-client-02",
        isBillable: false,
        isPublic: false,
        isActive: true,
        color: "#c56bff",
        estimate: {
          estimate: "PT0S",
          type: "AUTO",
        },
        userIds: [CLOCKIFY_USER_ID_FAKE],
        entryCount: 0,
        linkedId: "2002",
        isIncluded: false,
        memberOf: EntityGroup.Projects,
      },
      "clock-project-03": {
        id: "clock-project-03",
        name: "Test Project C",
        workspaceId: CLOCKIFY_WORKSPACE_ID_FAKE,
        clientId: "",
        isBillable: false,
        isPublic: false,
        isActive: false,
        color: "#04bb9b",
        estimate: {
          estimate: "PT0S",
          type: "AUTO",
        },
        userIds: [CLOCKIFY_USER_ID_FAKE],
        entryCount: 0,
        linkedId: "2003",
        isIncluded: false,
        memberOf: EntityGroup.Projects,
      },
      "clock-project-04": {
        id: "clock-project-04",
        name: "Test Project D",
        workspaceId: CLOCKIFY_WORKSPACE_ID_FAKE,
        clientId: "",
        isBillable: false,
        isPublic: false,
        isActive: true,
        color: "#04bb9b",
        estimate: {
          estimate: "PT0S",
          type: "MANUAL",
        },
        userIds: [CLOCKIFY_USER_ID_FAKE],
        entryCount: 0,
        linkedId: "2004",
        isIncluded: false,
        memberOf: EntityGroup.Projects,
      },
      "clock-project-05": {
        id: "clock-project-05",
        name: "Test Project E",
        workspaceId: CLOCKIFY_WORKSPACE_ID_FAKE,
        clientId: "",
        isBillable: false,
        isPublic: false,
        isActive: true,
        color: "#205500",
        estimate: {
          estimate: "PT0S",
          type: "AUTO",
        },
        userIds: [CLOCKIFY_USER_ID_FAKE],
        entryCount: 0,
        linkedId: "2005",
        isIncluded: false,
        memberOf: EntityGroup.Projects,
      },
      "clock-project-06": {
        id: "clock-project-06",
        name: "Test Project F",
        workspaceId: CLOCKIFY_WORKSPACE_ID_FAKE,
        clientId: "",
        isBillable: false,
        isPublic: false,
        isActive: true,
        color: "#a01aa5",
        estimate: {
          estimate: "PT0S",
          type: "AUTO",
        },
        userIds: [CLOCKIFY_USER_ID_FAKE],
        entryCount: 0,
        linkedId: "2006",
        isIncluded: false,
        memberOf: EntityGroup.Projects,
      },
    },
    isFetching: false,
  },
  tags: {
    source: {
      [TOGGL_TAG_ID_FAKE]: {
        ...TOGGL_TAG_FAKE,
      },
      "4002": {
        id: "4002",
        name: "tag-b",
        workspaceId: TOGGL_WORKSPACE_ID_FAKE,
        entryCount: 1,
        linkedId: "clock-tag-02",
        isIncluded: false,
        memberOf: EntityGroup.Tags,
      },
      "4003": {
        id: "4003",
        name: "tag-c",
        workspaceId: TOGGL_WORKSPACE_ID_FAKE,
        entryCount: 1,
        linkedId: "clock-tag-03",
        isIncluded: false,
        memberOf: EntityGroup.Tags,
      },
      "4004": {
        id: "4004",
        name: "tag-d",
        workspaceId: TOGGL_WORKSPACE_ID_FAKE,
        entryCount: 0,
        linkedId: "clock-tag-04",
        isIncluded: false,
        memberOf: EntityGroup.Tags,
      },
      "4005": {
        id: "4005",
        name: "tag-e",
        workspaceId: TOGGL_WORKSPACE_ID_FAKE,
        entryCount: 0,
        linkedId: "clock-tag-05",
        isIncluded: false,
        memberOf: EntityGroup.Tags,
      },
      "4006": {
        id: "4006",
        name: "tag-f",
        workspaceId: TOGGL_WORKSPACE_ID_FAKE,
        entryCount: 0,
        linkedId: null,
        isIncluded: true,
        memberOf: EntityGroup.Tags,
      },
      "4007": {
        id: "4007",
        name: "tag-g",
        workspaceId: TOGGL_WORKSPACE_ID_FAKE,
        entryCount: 0,
        linkedId: null,
        isIncluded: true,
        memberOf: EntityGroup.Tags,
      },
      "4008": {
        id: "4008",
        name: "tag-h",
        workspaceId: TOGGL_WORKSPACE_ID_FAKE,
        entryCount: 0,
        linkedId: null,
        isIncluded: true,
        memberOf: EntityGroup.Tags,
      },
      "4009": {
        id: "4009",
        name: "tag-i",
        workspaceId: TOGGL_WORKSPACE_ID_FAKE,
        entryCount: 0,
        linkedId: null,
        isIncluded: true,
        memberOf: EntityGroup.Tags,
      },
    },
    target: {
      [CLOCKIFY_TAG_ID_FAKE]: {
        ...CLOCKIFY_TAG_FAKE,
      },
      "clock-tag-02": {
        id: "clock-tag-02",
        name: "tag-b",
        workspaceId: CLOCKIFY_WORKSPACE_ID_FAKE,
        entryCount: 0,
        linkedId: "4002",
        isIncluded: false,
        memberOf: EntityGroup.Tags,
      },
      "clock-tag-03": {
        id: "clock-tag-03",
        name: "tag-c",
        workspaceId: CLOCKIFY_WORKSPACE_ID_FAKE,
        entryCount: 0,
        linkedId: "4003",
        isIncluded: false,
        memberOf: EntityGroup.Tags,
      },
      "clock-tag-04": {
        id: "clock-tag-04",
        name: "tag-d",
        workspaceId: CLOCKIFY_WORKSPACE_ID_FAKE,
        entryCount: 0,
        linkedId: "4004",
        isIncluded: false,
        memberOf: EntityGroup.Tags,
      },
      "clock-tag-05": {
        id: "clock-tag-05",
        name: "tag-e",
        workspaceId: CLOCKIFY_WORKSPACE_ID_FAKE,
        entryCount: 0,
        linkedId: "4005",
        isIncluded: false,
        memberOf: EntityGroup.Tags,
      },
    },
    isFetching: false,
  },
  tasks: {
    source: {
      [TOGGL_TASK_ID_FAKE]: {
        ...TOGGL_TASK_FAKE,
      },
      "7002": {
        id: "7002",
        name: "Task 2",
        estimate: "PT0M",
        projectId: TOGGL_PROJECT_ID_FAKE,
        assigneeIds: [],
        isActive: true,
        workspaceId: TOGGL_WORKSPACE_ID_FAKE,
        entryCount: 1,
        linkedId: "clock-task-02",
        isIncluded: false,
        memberOf: EntityGroup.Tasks,
      },
      "7003": {
        id: "7003",
        name: "Task 3",
        estimate: "PT6H",
        projectId: "2002",
        assigneeIds: [],
        isActive: true,
        workspaceId: TOGGL_WORKSPACE_ID_FAKE,
        entryCount: 1,
        linkedId: "clock-task-03",
        isIncluded: false,
        memberOf: EntityGroup.Tasks,
      },
      "7004": {
        id: "7004",
        name: "Task 4",
        estimate: "PT6H",
        projectId: "2003",
        assigneeIds: [],
        isActive: true,
        workspaceId: TOGGL_WORKSPACE_ID_FAKE,
        entryCount: 1,
        linkedId: "clock-task-04",
        isIncluded: false,
        memberOf: EntityGroup.Tasks,
      },
      "7005": {
        id: "7005",
        name: "Task 5",
        estimate: "PT6H",
        projectId: "2004",
        assigneeIds: [],
        isActive: true,
        workspaceId: TOGGL_WORKSPACE_ID_FAKE,
        entryCount: 3,
        linkedId: "clock-task-05",
        isIncluded: false,
        memberOf: EntityGroup.Tasks,
      },
    },
    target: {
      [CLOCKIFY_TASK_ID_FAKE]: {
        ...CLOCKIFY_TASK_FAKE,
      },
      "clock-task-02": {
        id: "clock-task-02",
        name: "Task 2",
        estimate: "PT1H",
        projectId: CLOCKIFY_PROJECT_ID_FAKE,
        assigneeIds: [CLOCKIFY_USER_ID_FAKE],
        isActive: false,
        workspaceId: CLOCKIFY_WORKSPACE_ID_FAKE,
        entryCount: 0,
        linkedId: "7002",
        isIncluded: false,
        memberOf: EntityGroup.Tasks,
      },
      "clock-task-03": {
        id: "clock-task-03",
        name: "Task 3",
        estimate: "PT2H10M",
        projectId: CLOCKIFY_PROJECT_ID_FAKE,
        assigneeIds: [CLOCKIFY_USER_ID_FAKE],
        isActive: true,
        workspaceId: CLOCKIFY_WORKSPACE_ID_FAKE,
        entryCount: 0,
        linkedId: "7003",
        isIncluded: false,
        memberOf: EntityGroup.Tasks,
      },
      "clock-task-04": {
        id: "clock-task-04",
        name: "Task 4",
        estimate: "PT2H20M",
        projectId: "clock-project-02",
        assigneeIds: [CLOCKIFY_USER_ID_FAKE],
        isActive: true,
        workspaceId: CLOCKIFY_WORKSPACE_ID_FAKE,
        entryCount: 0,
        linkedId: "7004",
        isIncluded: false,
        memberOf: EntityGroup.Tasks,
      },
      "clock-task-05": {
        id: "clock-task-05",
        name: "Task 5",
        estimate: "PT4H15M30S",
        projectId: "clock-project-02",
        assigneeIds: [CLOCKIFY_USER_ID_FAKE],
        isActive: false,
        workspaceId: CLOCKIFY_WORKSPACE_ID_FAKE,
        entryCount: 0,
        linkedId: "7005",
        isIncluded: false,
        memberOf: EntityGroup.Tasks,
      },
    },
    isFetching: false,
  },
  timeEntries: {
    source: {
      [TOGGL_TIME_ENTRY_ID_FAKE]: {
        ...TOGGL_TIME_ENTRY_FAKE,
      },
      "8002": {
        id: "8002",
        description: "This is a test entry (02)",
        isBillable: false,
        start: new Date("2019-06-24T14:00:00.000Z"),
        end: new Date("2019-06-24T22:00:00.000Z"),
        year: 2019,
        isActive: false,
        clientId: TOGGL_CLIENT_ID_FAKE,
        projectId: TOGGL_PROJECT_ID_FAKE,
        tagIds: [],
        tagNames: [],
        taskId: TOGGL_TASK_ID_FAKE,
        userId: TOGGL_USER_ID_FAKE,
        userGroupIds: [],
        workspaceId: TOGGL_WORKSPACE_ID_FAKE,
        entryCount: 0,
        linkedId: "clock-entry-02",
        isIncluded: false,
        memberOf: EntityGroup.TimeEntries,
      },
      "8003": {
        id: "8003",
        description: "This is a test entry (03)",
        isBillable: false,
        start: new Date("2019-06-23T14:30:00.000Z"),
        end: new Date("2019-06-24T04:30:00.000Z"),
        year: 2019,
        isActive: false,
        clientId: TOGGL_CLIENT_ID_FAKE,
        projectId: TOGGL_PROJECT_ID_FAKE,
        tagIds: ["4003"],
        tagNames: ["tag-c"],
        taskId: "7002",
        userId: TOGGL_USER_ID_FAKE,
        userGroupIds: [],
        workspaceId: TOGGL_WORKSPACE_ID_FAKE,
        entryCount: 0,
        linkedId: "clock-entry-03",
        isIncluded: false,
        memberOf: EntityGroup.TimeEntries,
      },
      "8004": {
        id: "8004",
        description: "This is a test entry (04)",
        isBillable: false,
        start: new Date("2019-06-23T14:00:20.000Z"),
        end: new Date("2019-06-23T17:05:20.000Z"),
        year: 2019,
        isActive: false,
        clientId: "3002",
        projectId: "2002",
        tagIds: [],
        tagNames: [],
        taskId: null,
        userId: TOGGL_USER_ID_FAKE,
        userGroupIds: [],
        workspaceId: TOGGL_WORKSPACE_ID_FAKE,
        entryCount: 0,
        linkedId: "clock-entry-04",
        isIncluded: false,
        memberOf: EntityGroup.TimeEntries,
      },
      "8005": {
        id: "8005",
        description: "This is a test entry (05)",
        isBillable: false,
        start: new Date("2019-06-22T14:00:19.000Z"),
        end: new Date("2019-06-22T19:15:19.000Z"),
        year: 2019,
        isActive: false,
        clientId: "3002",
        projectId: "2002",
        tagIds: [],
        tagNames: [],
        taskId: null,
        userId: TOGGL_USER_ID_FAKE,
        userGroupIds: [],
        workspaceId: TOGGL_WORKSPACE_ID_FAKE,
        entryCount: 0,
        linkedId: "clock-entry-05",
        isIncluded: false,
        memberOf: EntityGroup.TimeEntries,
      },
      "8006": {
        id: "8006",
        description: "This is a test entry (06)",
        isBillable: false,
        start: new Date("2019-06-21T20:45:57.000Z"),
        end: new Date("2019-06-21T21:50:57.000Z"),
        year: 2019,
        isActive: false,
        clientId: "3002",
        projectId: "2002",
        tagIds: [],
        tagNames: [],
        taskId: "7003",
        userId: TOGGL_USER_ID_FAKE,
        userGroupIds: [],
        workspaceId: TOGGL_WORKSPACE_ID_FAKE,
        entryCount: 0,
        linkedId: "clock-entry-06",
        isIncluded: false,
        memberOf: EntityGroup.TimeEntries,
      },
      "8007": {
        id: "8007",
        description: "This is a test entry (07)",
        isBillable: false,
        start: new Date("2019-05-02T10:00:00.000Z"),
        end: new Date("2019-05-02T12:00:00.000Z"),
        year: 2019,
        isActive: false,
        clientId: null,
        projectId: "2003",
        tagIds: [],
        tagNames: [],
        taskId: "7004",
        userId: TOGGL_USER_ID_FAKE,
        userGroupIds: [],
        workspaceId: TOGGL_WORKSPACE_ID_FAKE,
        entryCount: 0,
        linkedId: "clock-entry-07",
        isIncluded: false,
        memberOf: EntityGroup.TimeEntries,
      },
      "8008": {
        id: "8008",
        description: "This is a test entry (08)",
        isBillable: false,
        start: new Date("2019-05-01T20:00:00.000Z"),
        end: new Date("2019-05-01T21:00:00.000Z"),
        year: 2019,
        isActive: false,
        clientId: null,
        projectId: "2003",
        tagIds: [],
        tagNames: [],
        taskId: null,
        userId: TOGGL_USER_ID_FAKE,
        userGroupIds: [],
        workspaceId: TOGGL_WORKSPACE_ID_FAKE,
        entryCount: 0,
        linkedId: "clock-entry-08",
        isIncluded: false,
        memberOf: EntityGroup.TimeEntries,
      },
      "8009": {
        id: "8009",
        description: "This is a test entry (09)",
        isBillable: false,
        start: new Date("2018-06-25T18:00:00.000Z"),
        end: new Date("2018-06-25T23:00:00.000Z"),
        year: 2018,
        isActive: false,
        clientId: null,
        projectId: "2003",
        tagIds: [],
        tagNames: [],
        taskId: null,
        userId: TOGGL_USER_ID_FAKE,
        userGroupIds: [],
        workspaceId: TOGGL_WORKSPACE_ID_FAKE,
        entryCount: 0,
        linkedId: "clock-entry-09",
        isIncluded: false,
        memberOf: EntityGroup.TimeEntries,
      },
      "8010": {
        id: "8010",
        description: "This is a test entry (10)",
        isBillable: false,
        start: new Date("2018-06-24T14:00:00.000Z"),
        end: new Date("2018-06-24T22:00:00.000Z"),
        year: 2018,
        isActive: false,
        clientId: null,
        projectId: "2004",
        tagIds: [],
        tagNames: [],
        taskId: "7005",
        userId: TOGGL_USER_ID_FAKE,
        userGroupIds: [],
        workspaceId: TOGGL_WORKSPACE_ID_FAKE,
        entryCount: 0,
        linkedId: "clock-entry-10",
        isIncluded: false,
        memberOf: EntityGroup.TimeEntries,
      },
      "8011": {
        id: "8011",
        description: "This is a test entry (11)",
        isBillable: false,
        start: new Date("2018-06-23T14:30:00.000Z"),
        end: new Date("2018-06-24T04:30:00.000Z"),
        year: 2018,
        isActive: false,
        clientId: null,
        projectId: "2004",
        tagIds: [],
        tagNames: [],
        taskId: "7005",
        userId: TOGGL_USER_ID_FAKE,
        userGroupIds: [],
        workspaceId: TOGGL_WORKSPACE_ID_FAKE,
        entryCount: 0,
        linkedId: "clock-entry-11",
        isIncluded: false,
        memberOf: EntityGroup.TimeEntries,
      },
      "8012": {
        id: "8012",
        description: "This is a test entry (12)",
        isBillable: false,
        start: new Date("2018-06-23T14:00:20.000Z"),
        end: new Date("2018-06-23T17:05:20.000Z"),
        year: 2018,
        isActive: false,
        clientId: null,
        projectId: "2004",
        tagIds: [],
        tagNames: [],
        taskId: "7005",
        userId: TOGGL_USER_ID_FAKE,
        userGroupIds: [],
        workspaceId: TOGGL_WORKSPACE_ID_FAKE,
        entryCount: 0,
        linkedId: "clock-entry-12",
        isIncluded: false,
        memberOf: EntityGroup.TimeEntries,
      },
      "8013": {
        id: "8013",
        description: "This is a test entry (13)",
        isBillable: false,
        start: new Date("2018-06-22T14:00:19.000Z"),
        end: new Date("2018-06-22T19:15:19.000Z"),
        year: 2018,
        isActive: false,
        clientId: null,
        projectId: "2005",
        tagIds: [],
        tagNames: [],
        taskId: null,
        userId: TOGGL_USER_ID_FAKE,
        userGroupIds: [],
        workspaceId: TOGGL_WORKSPACE_ID_FAKE,
        entryCount: 0,
        linkedId: "clock-entry-13",
        isIncluded: false,
        memberOf: EntityGroup.TimeEntries,
      },
      "8014": {
        id: "8014",
        description: "This is a test entry (14)",
        isBillable: false,
        start: new Date("2018-06-21T20:45:57.000Z"),
        end: new Date("2018-06-21T21:50:57.000Z"),
        year: 2018,
        isActive: false,
        clientId: null,
        projectId: "2005",
        tagIds: [],
        tagNames: [],
        taskId: null,
        userId: TOGGL_USER_ID_FAKE,
        userGroupIds: [],
        workspaceId: TOGGL_WORKSPACE_ID_FAKE,
        entryCount: 0,
        linkedId: "clock-entry-14",
        isIncluded: false,
        memberOf: EntityGroup.TimeEntries,
      },
      "8015": {
        id: "8015",
        description: "This is a test entry (15)",
        isBillable: false,
        start: new Date("2017-06-25T18:00:00.000Z"),
        end: new Date("2017-06-25T23:00:00.000Z"),
        year: 2017,
        isActive: false,
        clientId: null,
        projectId: "2005",
        tagIds: [],
        tagNames: [],
        taskId: null,
        userId: TOGGL_USER_ID_FAKE,
        userGroupIds: [],
        workspaceId: TOGGL_WORKSPACE_ID_FAKE,
        entryCount: 0,
        linkedId: "clock-entry-15",
        isIncluded: false,
        memberOf: EntityGroup.TimeEntries,
      },
      "8016": {
        id: "8016",
        description: "This is a test entry (16)",
        isBillable: false,
        start: new Date("2017-06-24T14:00:00.000Z"),
        end: new Date("2017-06-24T22:00:00.000Z"),
        year: 2017,
        isActive: false,
        clientId: null,
        projectId: "2005",
        tagIds: [],
        tagNames: [],
        taskId: null,
        userId: TOGGL_USER_ID_FAKE,
        userGroupIds: [],
        workspaceId: TOGGL_WORKSPACE_ID_FAKE,
        entryCount: 0,
        linkedId: "clock-entry-16",
        isIncluded: false,
        memberOf: EntityGroup.TimeEntries,
      },
      "8017": {
        id: "8017",
        description: "This is a test entry (17)",
        isBillable: false,
        start: new Date("2017-06-23T14:30:00.000Z"),
        end: new Date("2017-06-24T04:30:00.000Z"),
        year: 2017,
        isActive: false,
        clientId: null,
        projectId: "2006",
        tagIds: [],
        tagNames: [],
        taskId: null,
        userId: TOGGL_USER_ID_FAKE,
        userGroupIds: [],
        workspaceId: TOGGL_WORKSPACE_ID_FAKE,
        entryCount: 0,
        linkedId: "clock-entry-17",
        isIncluded: false,
        memberOf: EntityGroup.TimeEntries,
      },
      "8018": {
        id: "8018",
        description: "This is a test entry (18)",
        isBillable: false,
        start: new Date("2017-06-23T14:00:20.000Z"),
        end: new Date("2017-06-23T17:05:20.000Z"),
        year: 2017,
        isActive: false,
        clientId: null,
        projectId: "2006",
        tagIds: [],
        tagNames: [],
        taskId: null,
        userId: TOGGL_USER_ID_FAKE,
        userGroupIds: [],
        workspaceId: TOGGL_WORKSPACE_ID_FAKE,
        entryCount: 0,
        linkedId: "clock-entry-18",
        isIncluded: false,
        memberOf: EntityGroup.TimeEntries,
      },
      "8019": {
        id: "8019",
        description: "This is a test entry (19)",
        isBillable: false,
        start: new Date("2017-06-22T14:00:19.000Z"),
        end: new Date("2017-06-22T19:15:19.000Z"),
        year: 2017,
        isActive: false,
        clientId: null,
        projectId: "2006",
        tagIds: [],
        tagNames: [],
        taskId: null,
        userId: TOGGL_USER_ID_FAKE,
        userGroupIds: [],
        workspaceId: TOGGL_WORKSPACE_ID_FAKE,
        entryCount: 0,
        linkedId: "clock-entry-19",
        isIncluded: false,
        memberOf: EntityGroup.TimeEntries,
      },
      "8020": {
        id: "8020",
        description: "This is a test entry (20)",
        isBillable: false,
        start: new Date("2017-06-21T20:45:57.000Z"),
        end: new Date("2017-06-21T21:50:57.000Z"),
        year: 2017,
        isActive: false,
        clientId: null,
        projectId: "2006",
        tagIds: [],
        tagNames: [],
        taskId: null,
        userId: TOGGL_USER_ID_FAKE,
        userGroupIds: [],
        workspaceId: TOGGL_WORKSPACE_ID_FAKE,
        entryCount: 0,
        linkedId: "clock-entry-20",
        isIncluded: false,
        memberOf: EntityGroup.TimeEntries,
      },
    },
    target: {
      "clock-entry-20": {
        id: "clock-entry-20",
        description: "This is a test entry (20)",
        isBillable: false,
        start: new Date("2017-06-21T20:45:57.000Z"),
        end: new Date("2017-06-21T21:50:57.000Z"),
        year: 2017,
        isActive: false,
        clientId: "",
        projectId: "clock-project-06",
        tagIds: [],
        tagNames: [],
        taskId: null,
        userId: CLOCKIFY_USER_ID_FAKE,
        userGroupIds: [],
        workspaceId: CLOCKIFY_WORKSPACE_ID_FAKE,
        entryCount: 0,
        linkedId: "8020",
        isIncluded: true,
        memberOf: EntityGroup.TimeEntries,
      },
      "clock-entry-19": {
        id: "clock-entry-19",
        description: "This is a test entry (19)",
        isBillable: false,
        start: new Date("2017-06-22T14:00:19.000Z"),
        end: new Date("2017-06-22T19:15:19.000Z"),
        year: 2017,
        isActive: false,
        clientId: "",
        projectId: "clock-project-06",
        tagIds: [],
        tagNames: [],
        taskId: null,
        userId: CLOCKIFY_USER_ID_FAKE,
        userGroupIds: [],
        workspaceId: CLOCKIFY_WORKSPACE_ID_FAKE,
        entryCount: 0,
        linkedId: "8019",
        isIncluded: true,
        memberOf: EntityGroup.TimeEntries,
      },
      "clock-entry-18": {
        id: "clock-entry-18",
        description: "This is a test entry (18)",
        isBillable: false,
        start: new Date("2017-06-23T14:00:20.000Z"),
        end: new Date("2017-06-23T17:05:20.000Z"),
        year: 2017,
        isActive: false,
        clientId: "",
        projectId: "clock-project-06",
        tagIds: [],
        tagNames: [],
        taskId: null,
        userId: CLOCKIFY_USER_ID_FAKE,
        userGroupIds: [],
        workspaceId: CLOCKIFY_WORKSPACE_ID_FAKE,
        entryCount: 0,
        linkedId: "8018",
        isIncluded: true,
        memberOf: EntityGroup.TimeEntries,
      },
      "clock-entry-17": {
        id: "clock-entry-17",
        description: "This is a test entry (17)",
        isBillable: false,
        start: new Date("2017-06-23T14:30:00.000Z"),
        end: new Date("2017-06-24T04:30:00.000Z"),
        year: 2017,
        isActive: false,
        clientId: "",
        projectId: "clock-project-06",
        tagIds: [],
        tagNames: [],
        taskId: null,
        userId: CLOCKIFY_USER_ID_FAKE,
        userGroupIds: [],
        workspaceId: CLOCKIFY_WORKSPACE_ID_FAKE,
        entryCount: 0,
        linkedId: "8017",
        isIncluded: true,
        memberOf: EntityGroup.TimeEntries,
      },
      "clock-entry-16": {
        id: "clock-entry-16",
        description: "This is a test entry (16)",
        isBillable: false,
        start: new Date("2017-06-24T14:00:00.000Z"),
        end: new Date("2017-06-24T22:00:00.000Z"),
        year: 2017,
        isActive: false,
        clientId: "",
        projectId: "clock-project-05",
        tagIds: [],
        tagNames: [],
        taskId: null,
        userId: CLOCKIFY_USER_ID_FAKE,
        userGroupIds: [],
        workspaceId: CLOCKIFY_WORKSPACE_ID_FAKE,
        entryCount: 0,
        linkedId: "8016",
        isIncluded: true,
        memberOf: EntityGroup.TimeEntries,
      },
      "clock-entry-15": {
        id: "clock-entry-15",
        description: "This is a test entry (15)",
        isBillable: false,
        start: new Date("2017-06-25T18:00:00.000Z"),
        end: new Date("2017-06-25T23:00:00.000Z"),
        year: 2017,
        isActive: false,
        clientId: "",
        projectId: "clock-project-05",
        tagIds: [],
        tagNames: [],
        taskId: null,
        userId: CLOCKIFY_USER_ID_FAKE,
        userGroupIds: [],
        workspaceId: CLOCKIFY_WORKSPACE_ID_FAKE,
        entryCount: 0,
        linkedId: "8015",
        isIncluded: true,
        memberOf: EntityGroup.TimeEntries,
      },
      "clock-entry-14": {
        id: "clock-entry-14",
        description: "This is a test entry (14)",
        isBillable: false,
        start: new Date("2018-06-21T20:45:57.000Z"),
        end: new Date("2018-06-21T21:50:57.000Z"),
        year: 2018,
        isActive: false,
        clientId: "",
        projectId: "clock-project-05",
        tagIds: [],
        tagNames: [],
        taskId: null,
        userId: CLOCKIFY_USER_ID_FAKE,
        userGroupIds: [],
        workspaceId: CLOCKIFY_WORKSPACE_ID_FAKE,
        entryCount: 0,
        linkedId: "8014",
        isIncluded: true,
        memberOf: EntityGroup.TimeEntries,
      },
      "clock-entry-13": {
        id: "clock-entry-13",
        description: "This is a test entry (13)",
        isBillable: false,
        start: new Date("2018-06-22T14:00:19.000Z"),
        end: new Date("2018-06-22T19:15:19.000Z"),
        year: 2018,
        isActive: false,
        clientId: "",
        projectId: "clock-project-05",
        tagIds: [],
        tagNames: [],
        taskId: null,
        userId: CLOCKIFY_USER_ID_FAKE,
        userGroupIds: [],
        workspaceId: CLOCKIFY_WORKSPACE_ID_FAKE,
        entryCount: 0,
        linkedId: "8013",
        isIncluded: true,
        memberOf: EntityGroup.TimeEntries,
      },
      "clock-entry-12": {
        id: "clock-entry-12",
        description: "This is a test entry (12)",
        isBillable: false,
        start: new Date("2018-06-23T14:00:20.000Z"),
        end: new Date("2018-06-23T17:05:20.000Z"),
        year: 2018,
        isActive: false,
        clientId: "",
        projectId: "clock-project-04",
        tagIds: [],
        tagNames: [],
        taskId: null,
        userId: CLOCKIFY_USER_ID_FAKE,
        userGroupIds: [],
        workspaceId: CLOCKIFY_WORKSPACE_ID_FAKE,
        entryCount: 0,
        linkedId: "8012",
        isIncluded: true,
        memberOf: EntityGroup.TimeEntries,
      },
      "clock-entry-11": {
        id: "clock-entry-11",
        description: "This is a test entry (11)",
        isBillable: false,
        start: new Date("2018-06-23T14:30:00.000Z"),
        end: new Date("2018-06-24T04:30:00.000Z"),
        year: 2018,
        isActive: false,
        clientId: "",
        projectId: "clock-project-04",
        tagIds: [],
        tagNames: [],
        taskId: null,
        userId: CLOCKIFY_USER_ID_FAKE,
        userGroupIds: [],
        workspaceId: CLOCKIFY_WORKSPACE_ID_FAKE,
        entryCount: 0,
        linkedId: "8011",
        isIncluded: true,
        memberOf: EntityGroup.TimeEntries,
      },
      "clock-entry-10": {
        id: "clock-entry-10",
        description: "This is a test entry (10)",
        isBillable: false,
        start: new Date("2018-06-24T14:00:00.000Z"),
        end: new Date("2018-06-24T22:00:00.000Z"),
        year: 2018,
        isActive: false,
        clientId: "",
        projectId: "clock-project-04",
        tagIds: [],
        tagNames: [],
        taskId: null,
        userId: CLOCKIFY_USER_ID_FAKE,
        userGroupIds: [],
        workspaceId: CLOCKIFY_WORKSPACE_ID_FAKE,
        entryCount: 0,
        linkedId: "8010",
        isIncluded: true,
        memberOf: EntityGroup.TimeEntries,
      },
      "clock-entry-09": {
        id: "clock-entry-09",
        description: "This is a test entry (09)",
        isBillable: false,
        start: new Date("2018-06-25T18:00:00.000Z"),
        end: new Date("2018-06-25T23:00:00.000Z"),
        year: 2018,
        isActive: false,
        clientId: "",
        projectId: "clock-project-03",
        tagIds: ["clock-tag-03", "clock-tag-04", "clock-tag-05"],
        tagNames: ["tag-c", "tag-d", "tag-e"],
        taskId: null,
        userId: CLOCKIFY_USER_ID_FAKE,
        userGroupIds: [],
        workspaceId: CLOCKIFY_WORKSPACE_ID_FAKE,
        entryCount: 0,
        linkedId: "8009",
        isIncluded: true,
        memberOf: EntityGroup.TimeEntries,
      },
      "clock-entry-08": {
        id: "clock-entry-08",
        description: "This is a test entry (08)",
        isBillable: false,
        start: new Date("2019-05-01T20:00:00.000Z"),
        end: new Date("2019-05-01T21:00:00.000Z"),
        year: 2019,
        isActive: false,
        clientId: "",
        projectId: "clock-project-03",
        tagIds: [],
        tagNames: [],
        taskId: null,
        userId: CLOCKIFY_USER_ID_FAKE,
        userGroupIds: [],
        workspaceId: CLOCKIFY_WORKSPACE_ID_FAKE,
        entryCount: 0,
        linkedId: "8008",
        isIncluded: true,
        memberOf: EntityGroup.TimeEntries,
      },
      "clock-entry-07": {
        id: "clock-entry-07",
        description: "This is a test entry (07)",
        isBillable: false,
        start: new Date("2019-05-02T10:00:00.000Z"),
        end: new Date("2019-05-02T12:00:00.000Z"),
        year: 2019,
        isActive: false,
        clientId: "",
        projectId: "clock-project-03",
        tagIds: [],
        tagNames: [],
        taskId: null,
        userId: CLOCKIFY_USER_ID_FAKE,
        userGroupIds: [],
        workspaceId: CLOCKIFY_WORKSPACE_ID_FAKE,
        entryCount: 0,
        linkedId: "8007",
        isIncluded: true,
        memberOf: EntityGroup.TimeEntries,
      },
      "clock-entry-06": {
        id: "clock-entry-06",
        description: "This is a test entry (06)",
        isBillable: false,
        start: new Date("2019-06-21T20:45:57.000Z"),
        end: new Date("2019-06-21T21:50:57.000Z"),
        year: 2019,
        isActive: false,
        clientId: "clock-client-02",
        projectId: "clock-project-02",
        tagIds: ["clock-tag-03", "clock-tag-04"],
        tagNames: ["tag-c", "tag-d"],
        taskId: "clock-task-05",
        userId: CLOCKIFY_USER_ID_FAKE,
        userGroupIds: [],
        workspaceId: CLOCKIFY_WORKSPACE_ID_FAKE,
        entryCount: 0,
        linkedId: "8006",
        isIncluded: true,
        memberOf: EntityGroup.TimeEntries,
      },
      "clock-entry-05": {
        id: "clock-entry-05",
        description: "This is a test entry (05)",
        isBillable: false,
        start: new Date("2019-06-22T14:00:19.000Z"),
        end: new Date("2019-06-22T19:15:19.000Z"),
        year: 2019,
        isActive: false,
        clientId: "clock-client-02",
        projectId: "clock-project-02",
        tagIds: [],
        tagNames: [],
        taskId: "clock-task-04",
        userId: CLOCKIFY_USER_ID_FAKE,
        userGroupIds: [],
        workspaceId: CLOCKIFY_WORKSPACE_ID_FAKE,
        entryCount: 0,
        linkedId: "8005",
        isIncluded: true,
        memberOf: EntityGroup.TimeEntries,
      },
      "clock-entry-04": {
        id: "clock-entry-04",
        description: "This is a test entry (04)",
        isBillable: false,
        start: new Date("2019-06-23T14:00:20.000Z"),
        end: new Date("2019-06-23T17:05:20.000Z"),
        year: 2019,
        isActive: false,
        clientId: "clock-client-02",
        projectId: "clock-project-02",
        tagIds: ["clock-tag-02", "clock-tag-03"],
        tagNames: ["tag-b", "tag-c"],
        taskId: "clock-task-04",
        userId: CLOCKIFY_USER_ID_FAKE,
        userGroupIds: [],
        workspaceId: CLOCKIFY_WORKSPACE_ID_FAKE,
        entryCount: 0,
        linkedId: "8004",
        isIncluded: true,
        memberOf: EntityGroup.TimeEntries,
      },
      "clock-entry-03": {
        id: "clock-entry-03",
        description: "This is a test entry (03)",
        isBillable: false,
        start: new Date("2019-06-23T14:30:00.000Z"),
        end: new Date("2019-06-24T04:30:00.000Z"),
        year: 2019,
        isActive: false,
        clientId: CLOCKIFY_CLIENT_ID_FAKE,
        projectId: CLOCKIFY_PROJECT_ID_FAKE,
        tagIds: ["clock-tag-01"],
        tagNames: ["tag-a"],
        taskId: "clock-task-03",
        userId: CLOCKIFY_USER_ID_FAKE,
        userGroupIds: [],
        workspaceId: CLOCKIFY_WORKSPACE_ID_FAKE,
        entryCount: 0,
        linkedId: "8003",
        isIncluded: true,
        memberOf: EntityGroup.TimeEntries,
      },
      "clock-entry-02": {
        id: "clock-entry-02",
        description: "This is a test entry (02)",
        isBillable: false,
        start: new Date("2019-06-24T14:00:00.000Z"),
        end: new Date("2019-06-24T22:00:00.000Z"),
        year: 2019,
        isActive: false,
        clientId: CLOCKIFY_CLIENT_ID_FAKE,
        projectId: CLOCKIFY_PROJECT_ID_FAKE,
        tagIds: [],
        tagNames: [],
        taskId: "clock-task-02",
        userId: CLOCKIFY_USER_ID_FAKE,
        userGroupIds: [],
        workspaceId: CLOCKIFY_WORKSPACE_ID_FAKE,
        entryCount: 0,
        linkedId: "8002",
        isIncluded: true,
        memberOf: EntityGroup.TimeEntries,
      },
      [CLOCKIFY_TIME_ENTRY_ID_FAKE]: {
        ...CLOCKIFY_TIME_ENTRY_FAKE,
      },
    },
    isFetching: false,
    isDuplicateCheckEnabled: true,
  },
  userGroups: {
    source: {
      [TOGGL_USER_GROUP_ID_FAKE]: {
        ...TOGGL_USER_GROUP_FAKE,
      },
      "5002": {
        id: "5002",
        name: "Test Group B",
        userIds: [],
        workspaceId: TOGGL_WORKSPACE_ID_FAKE,
        entryCount: 0,
        linkedId: null,
        isIncluded: true,
        memberOf: EntityGroup.UserGroups,
      },
    },
    target: {
      [CLOCKIFY_USER_GROUP_ID_FAKE]: {
        ...CLOCKIFY_USER_GROUP_FAKE,
      },
      "clock-user-group-02": {
        id: "clock-user-group-02",
        name: "Test Group A",
        userIds: [],
        workspaceId: CLOCKIFY_WORKSPACE_ID_FAKE,
        entryCount: 0,
        linkedId: TOGGL_USER_GROUP_ID_FAKE,
        isIncluded: false,
        memberOf: EntityGroup.UserGroups,
      },
    },
    isFetching: false,
  },
  users: {
    source: {
      [TOGGL_USER_ID_FAKE]: {
        ...TOGGL_USER_FAKE,
      },
    },
    target: {
      [CLOCKIFY_USER_ID_FAKE]: {
        ...CLOCKIFY_USER_FAKE,
      },
    },
    isFetching: false,
  },
  workspaces: {
    source: {
      [TOGGL_WORKSPACE_ID_FAKE]: {
        ...TOGGL_WORKSPACE_FAKE,
      },
    },
    target: {
      [CLOCKIFY_WORKSPACE_ID_FAKE]: {
        ...CLOCKIFY_WORKSPACE_FAKE,
      },
    },
    activeWorkspaceId: TOGGL_WORKSPACE_ID_FAKE,
    isFetching: false,
  },
};

const INVALID_ACTION_FAKE = {
  type: "INVALID_ACTION" as AnyValid,
  payload: undefined,
};

export const FAKES = {
  CLOCKIFY_CLIENT_ID: CLOCKIFY_CLIENT_ID_FAKE,
  CLOCKIFY_PROJECT_ID: CLOCKIFY_PROJECT_ID_FAKE,
  CLOCKIFY_TAG_ID: CLOCKIFY_TAG_ID_FAKE,
  CLOCKIFY_TASK_ID: CLOCKIFY_TASK_ID_FAKE,
  CLOCKIFY_TIME_ENTRY_ID: CLOCKIFY_TIME_ENTRY_ID_FAKE,
  CLOCKIFY_USER_ID: CLOCKIFY_USER_ID_FAKE,
  CLOCKIFY_USER_GROUP_ID: CLOCKIFY_USER_GROUP_ID_FAKE,
  CLOCKIFY_WORKSPACE_ID: CLOCKIFY_WORKSPACE_ID_FAKE,
  TOGGL_CLIENT_ID: TOGGL_CLIENT_ID_FAKE,
  TOGGL_PROJECT_ID: TOGGL_PROJECT_ID_FAKE,
  TOGGL_TAG_ID: TOGGL_TAG_ID_FAKE,
  TOGGL_TASK_ID: TOGGL_TASK_ID_FAKE,
  TOGGL_TIME_ENTRY_ID: TOGGL_TIME_ENTRY_ID_FAKE,
  TOGGL_USER_ID: TOGGL_USER_ID_FAKE,
  TOGGL_USER_GROUP_ID: TOGGL_USER_GROUP_ID_FAKE,
  TOGGL_WORKSPACE_ID: TOGGL_WORKSPACE_ID_FAKE,
  CLOCKIFY_WORKSPACE: CLOCKIFY_WORKSPACE_FAKE,
  CLOCKIFY_CLIENT: CLOCKIFY_CLIENT_FAKE,
  CLOCKIFY_CREDENTIALS: CLOCKIFY_CREDENTIALS_FAKE,
  CLOCKIFY_PROJECT: CLOCKIFY_PROJECT_FAKE,
  CLOCKIFY_TAG: CLOCKIFY_TAG_FAKE,
  CLOCKIFY_TASK: CLOCKIFY_TASK_FAKE,
  CLOCKIFY_TIME_ENTRY: CLOCKIFY_TIME_ENTRY_FAKE,
  CLOCKIFY_USER: CLOCKIFY_USER_FAKE,
  CLOCKIFY_USER_GROUP: CLOCKIFY_USER_GROUP_FAKE,
  TOGGL_WORKSPACE: TOGGL_WORKSPACE_FAKE,
  TOGGL_CLIENT: TOGGL_CLIENT_FAKE,
  TOGGL_CREDENTIALS: TOGGL_CREDENTIALS_FAKE,
  TOGGL_PROJECT: TOGGL_PROJECT_FAKE,
  TOGGL_TAG: TOGGL_TAG_FAKE,
  TOGGL_TASK: TOGGL_TASK_FAKE,
  TOGGL_TIME_ENTRY: TOGGL_TIME_ENTRY_FAKE,
  TOGGL_USER: TOGGL_USER_FAKE,
  TOGGL_USER_GROUP: TOGGL_USER_GROUP_FAKE,
  INVALID_ACTION: INVALID_ACTION_FAKE,
  REDUX_STATE: REDUX_STATE_FAKE,
};
