/* eslint-disable */
// @ts-ignore
export default {
  allEntities: {
    areExistsInTargetShown: true,
    entityGroupInProcess: null,
    fetchAllFetchStatus: "PENDING",
    pushAllChangesFetchStatus: "PENDING",
    toolAction: "transfer",
    toolNameByMapping: {
      source: "toggl",
      target: "clockify",
    },
    transferCountsByEntityGroup: {
      clients: 0,
      tags: 0,
      projects: 0,
      tasks: 0,
      timeEntries: 0,
      users: 0,
      userGroups: 0,
    },
  },
  app: {
    notifications: [],
  },
  credentials: {
    source: {
      apiKey: "TOGGLAPIKEY",
      email: "test-user@test.com",
      userId: "6001",
    },
    target: {
      apiKey: "CLOCKIFYAPIKEY",
      email: "test-user@test.com",
      userId: "clock-user-01",
    },
    validationErrorsByMapping: {
      source: "Error getting source",
      target: "Error getting target",
    },
    validationFetchStatus: "PENDING",
  },
  clients: {
    source: {
      "3001": {
        id: "3001",
        name: "Test Client A",
        workspaceId: "1001",
        entryCount: 3,
        linkedId: "clock-client-01",
        isIncluded: false,
        memberOf: "clients",
      },
      "3002": {
        id: "3002",
        name: "Test Client B",
        workspaceId: "1001",
        entryCount: 3,
        linkedId: "clock-client-02",
        isIncluded: false,
        memberOf: "clients",
      },
    },
    target: {
      "clock-client-01": {
        id: "clock-client-01",
        name: "Test Client A",
        workspaceId: "clock-workspace-01",
        entryCount: 0,
        linkedId: "3001",
        isIncluded: false,
        memberOf: "clients",
      },
      "clock-client-02": {
        id: "clock-client-02",
        name: "Test Client B",
        workspaceId: "clock-workspace-01",
        entryCount: 0,
        linkedId: "3002",
        isIncluded: false,
        memberOf: "clients",
      },
    },
    isFetching: false,
  },
  projects: {
    source: {
      "2001": {
        id: "2001",
        name: "Test Project A",
        workspaceId: "1001",
        clientId: "3001",
        isBillable: false,
        isPublic: false,
        isActive: true,
        color: "#ea468d",
        estimate: {
          estimate: 0,
          type: "MANUAL",
        },
        userIds: ["6001"],
        entryCount: 3,
        linkedId: "clock-project-01",
        isIncluded: false,
        memberOf: "projects",
      },
      "2002": {
        id: "2002",
        name: "Test Project B",
        workspaceId: "1001",
        clientId: null,
        isBillable: false,
        isPublic: false,
        isActive: false,
        color: "#3750b5",
        estimate: {
          estimate: 40,
          type: "MANUAL",
        },
        userIds: ["6001"],
        entryCount: 3,
        linkedId: "clock-project-02",
        isIncluded: false,
        memberOf: "projects",
      },
      "2003": {
        id: "2003",
        name: "Test Project C",
        workspaceId: "1001",
        clientId: null,
        isBillable: false,
        isPublic: false,
        isActive: true,
        color: "#c56bff",
        estimate: {
          estimate: 0,
          type: "MANUAL",
        },
        userIds: ["6001"],
        entryCount: 3,
        linkedId: "clock-project-03",
        isIncluded: false,
        memberOf: "projects",
      },
      "2004": {
        id: "2004",
        name: "Test Project D",
        workspaceId: "1001",
        clientId: null,
        isBillable: false,
        isPublic: false,
        isActive: true,
        color: "#04bb9b",
        estimate: {
          estimate: 0,
          type: "MANUAL",
        },
        userIds: ["6001"],
        entryCount: 3,
        linkedId: "clock-project-04",
        isIncluded: false,
        memberOf: "projects",
      },
      "2005": {
        id: "2005",
        name: "Test Project E",
        workspaceId: "1001",
        clientId: null,
        isBillable: false,
        isPublic: false,
        isActive: true,
        color: "#205500",
        estimate: {
          estimate: 0,
          type: "MANUAL",
        },
        userIds: ["6001"],
        entryCount: 4,
        linkedId: "clock-project-05",
        isIncluded: false,
        memberOf: "projects",
      },
      "2006": {
        id: "2006",
        name: "Test Project F",
        workspaceId: "1001",
        clientId: null,
        isBillable: false,
        isPublic: false,
        isActive: true,
        color: "#a01aa5",
        estimate: {
          estimate: 0,
          type: "MANUAL",
        },
        userIds: ["6001"],
        entryCount: 4,
        linkedId: "clock-project-06",
        isIncluded: false,
        memberOf: "projects",
      },
    },
    target: {
      "clock-project-01": {
        id: "clock-project-01",
        name: "Test Project A",
        workspaceId: "clock-workspace-01",
        clientId: "clock-client-01",
        isBillable: false,
        isPublic: false,
        isActive: true,
        color: "#ea468d",
        estimate: {
          estimate: "PT0S",
          type: "AUTO",
        },
        userIds: ["clock-user-01"],
        entryCount: 0,
        linkedId: "2001",
        isIncluded: false,
        memberOf: "projects",
      },
      "clock-project-02": {
        id: "clock-project-02",
        name: "Test Project B",
        workspaceId: "clock-workspace-01",
        clientId: "clock-client-02",
        isBillable: false,
        isPublic: false,
        isActive: true,
        color: "#c56bff",
        estimate: {
          estimate: "PT0S",
          type: "AUTO",
        },
        userIds: ["clock-user-01"],
        entryCount: 0,
        linkedId: "2002",
        isIncluded: false,
        memberOf: "projects",
      },
      "clock-project-03": {
        id: "clock-project-03",
        name: "Test Project C",
        workspaceId: "clock-workspace-01",
        clientId: "",
        isBillable: false,
        isPublic: false,
        isActive: false,
        color: "#04bb9b",
        estimate: {
          estimate: "PT0S",
          type: "AUTO",
        },
        userIds: ["clock-user-01"],
        entryCount: 0,
        linkedId: "2003",
        isIncluded: false,
        memberOf: "projects",
      },
      "clock-project-04": {
        id: "clock-project-04",
        name: "Test Project D",
        workspaceId: "clock-workspace-01",
        clientId: "",
        isBillable: false,
        isPublic: false,
        isActive: true,
        color: "#04bb9b",
        estimate: {
          estimate: "PT0S",
          type: "MANUAL",
        },
        userIds: ["clock-user-01"],
        entryCount: 0,
        linkedId: "2004",
        isIncluded: false,
        memberOf: "projects",
      },
      "clock-project-05": {
        id: "clock-project-05",
        name: "Test Project E",
        workspaceId: "clock-workspace-01",
        clientId: "",
        isBillable: false,
        isPublic: false,
        isActive: true,
        color: "#205500",
        estimate: {
          estimate: "PT0S",
          type: "AUTO",
        },
        userIds: ["clock-user-01"],
        entryCount: 0,
        linkedId: "2005",
        isIncluded: false,
        memberOf: "projects",
      },
      "clock-project-06": {
        id: "clock-project-06",
        name: "Test Project F",
        workspaceId: "clock-workspace-01",
        clientId: "",
        isBillable: false,
        isPublic: false,
        isActive: true,
        color: "#a01aa5",
        estimate: {
          estimate: "PT0S",
          type: "AUTO",
        },
        userIds: ["clock-user-01"],
        entryCount: 0,
        linkedId: "2006",
        isIncluded: false,
        memberOf: "projects",
      },
    },
    isFetching: false,
  },
  router: {
    location: {
      pathname: "/select-inclusions",
      search: "",
      hash: "",
      key: "oq49zd",
      query: {},
    },
    action: "PUSH",
  },
  tags: {
    source: {
      "4001": {
        id: "4001",
        name: "tag-a",
        workspaceId: "1001",
        entryCount: 1,
        linkedId: "clock-tag-01",
        isIncluded: false,
        memberOf: "tags",
      },
      "4002": {
        id: "4002",
        name: "tag-b",
        workspaceId: "1001",
        entryCount: 1,
        linkedId: "clock-tag-02",
        isIncluded: false,
        memberOf: "tags",
      },
      "4003": {
        id: "4003",
        name: "tag-c",
        workspaceId: "1001",
        entryCount: 1,
        linkedId: "clock-tag-03",
        isIncluded: false,
        memberOf: "tags",
      },
      "4004": {
        id: "4004",
        name: "tag-d",
        workspaceId: "1001",
        entryCount: 0,
        linkedId: "clock-tag-04",
        isIncluded: false,
        memberOf: "tags",
      },
      "4005": {
        id: "4005",
        name: "tag-e",
        workspaceId: "1001",
        entryCount: 0,
        linkedId: "clock-tag-05",
        isIncluded: false,
        memberOf: "tags",
      },
      "4006": {
        id: "4006",
        name: "tag-f",
        workspaceId: "1001",
        entryCount: 0,
        linkedId: null,
        isIncluded: true,
        memberOf: "tags",
      },
      "4007": {
        id: "4007",
        name: "tag-g",
        workspaceId: "1001",
        entryCount: 0,
        linkedId: null,
        isIncluded: true,
        memberOf: "tags",
      },
      "4008": {
        id: "4008",
        name: "tag-h",
        workspaceId: "1001",
        entryCount: 0,
        linkedId: null,
        isIncluded: true,
        memberOf: "tags",
      },
      "4009": {
        id: "4009",
        name: "tag-i",
        workspaceId: "1001",
        entryCount: 0,
        linkedId: null,
        isIncluded: true,
        memberOf: "tags",
      },
    },
    target: {
      "clock-tag-01": {
        id: "clock-tag-01",
        name: "tag-a",
        workspaceId: "clock-workspace-01",
        entryCount: 0,
        linkedId: "4001",
        isIncluded: false,
        memberOf: "tags",
      },
      "clock-tag-02": {
        id: "clock-tag-02",
        name: "tag-b",
        workspaceId: "clock-workspace-01",
        entryCount: 0,
        linkedId: "4002",
        isIncluded: false,
        memberOf: "tags",
      },
      "clock-tag-03": {
        id: "clock-tag-03",
        name: "tag-c",
        workspaceId: "clock-workspace-01",
        entryCount: 0,
        linkedId: "4003",
        isIncluded: false,
        memberOf: "tags",
      },
      "clock-tag-04": {
        id: "clock-tag-04",
        name: "tag-d",
        workspaceId: "clock-workspace-01",
        entryCount: 0,
        linkedId: "4004",
        isIncluded: false,
        memberOf: "tags",
      },
      "clock-tag-05": {
        id: "clock-tag-05",
        name: "tag-e",
        workspaceId: "clock-workspace-01",
        entryCount: 0,
        linkedId: "4005",
        isIncluded: false,
        memberOf: "tags",
      },
    },
    isFetching: false,
  },
  tasks: {
    source: {
      "7001": {
        id: "7001",
        name: "Task 1",
        estimate: "PT2H",
        projectId: "2001",
        assigneeIds: ["123123"],
        isActive: true,
        workspaceId: "1001",
        entryCount: 2,
        linkedId: "clock-task-01",
        isIncluded: false,
        memberOf: "tasks",
      },
      "7002": {
        id: "7002",
        name: "Task 2",
        estimate: "PT0M",
        projectId: "2001",
        assigneeIds: [],
        isActive: true,
        workspaceId: "1001",
        entryCount: 1,
        linkedId: "clock-task-02",
        isIncluded: false,
        memberOf: "tasks",
      },
      "7003": {
        id: "7003",
        name: "Task 3",
        estimate: "PT6H",
        projectId: "2002",
        assigneeIds: [],
        isActive: true,
        workspaceId: "1001",
        entryCount: 1,
        linkedId: "clock-task-03",
        isIncluded: false,
        memberOf: "tasks",
      },
      "7004": {
        id: "7004",
        name: "Task 4",
        estimate: "PT6H",
        projectId: "2003",
        assigneeIds: [],
        isActive: true,
        workspaceId: "1001",
        entryCount: 1,
        linkedId: "clock-task-04",
        isIncluded: false,
        memberOf: "tasks",
      },
      "7005": {
        id: "7005",
        name: "Task 5",
        estimate: "PT6H",
        projectId: "2004",
        assigneeIds: [],
        isActive: true,
        workspaceId: "1001",
        entryCount: 3,
        linkedId: "clock-task-05",
        isIncluded: false,
        memberOf: "tasks",
      },
    },
    target: {
      "clock-task-01": {
        id: "clock-task-01",
        name: "Task 1",
        estimate: "PT1H30M15S",
        projectId: "clock-project-01",
        assigneeIds: ["clock-user-01"],
        isActive: true,
        workspaceId: "clock-workspace-01",
        entryCount: 0,
        linkedId: "7001",
        isIncluded: false,
        memberOf: "tasks",
      },
      "clock-task-02": {
        id: "clock-task-02",
        name: "Task 2",
        estimate: "PT1H",
        projectId: "clock-project-01",
        assigneeIds: ["clock-user-01"],
        isActive: false,
        workspaceId: "clock-workspace-01",
        entryCount: 0,
        linkedId: "7002",
        isIncluded: false,
        memberOf: "tasks",
      },
      "clock-task-03": {
        id: "clock-task-03",
        name: "Task 3",
        estimate: "PT2H10M",
        projectId: "clock-project-01",
        assigneeIds: ["clock-user-01"],
        isActive: true,
        workspaceId: "clock-workspace-01",
        entryCount: 0,
        linkedId: "7003",
        isIncluded: false,
        memberOf: "tasks",
      },
      "clock-task-04": {
        id: "clock-task-04",
        name: "Task 4",
        estimate: "PT2H20M",
        projectId: "clock-project-02",
        assigneeIds: ["clock-user-01"],
        isActive: true,
        workspaceId: "clock-workspace-01",
        entryCount: 0,
        linkedId: "7004",
        isIncluded: false,
        memberOf: "tasks",
      },
      "clock-task-05": {
        id: "clock-task-05",
        name: "Task 5",
        estimate: "PT4H15M30S",
        projectId: "clock-project-02",
        assigneeIds: ["clock-user-01"],
        isActive: false,
        workspaceId: "clock-workspace-01",
        entryCount: 0,
        linkedId: "7005",
        isIncluded: false,
        memberOf: "tasks",
      },
    },
    isFetching: false,
  },
  timeEntries: {
    source: {
      "8001": {
        id: "8001",
        description: "This is a test entry (01)",
        isBillable: false,
        start: "2019-06-25T18:00:00.000Z",
        end: "2019-06-25T23:00:00.000Z",
        year: 2019,
        isActive: false,
        clientId: "3001",
        projectId: "2001",
        tagIds: ["4001", "4002"],
        tagNames: ["tag-a", "tag-b"],
        taskId: "7001",
        userId: "6001",
        userGroupIds: [],
        workspaceId: "1001",
        entryCount: 0,
        linkedId: "clock-entry-01",
        isIncluded: false,
        memberOf: "timeEntries",
      },
      "8002": {
        id: "8002",
        description: "This is a test entry (02)",
        isBillable: false,
        start: "2019-06-24T14:00:00.000Z",
        end: "2019-06-24T22:00:00.000Z",
        year: 2019,
        isActive: false,
        clientId: "3001",
        projectId: "2001",
        tagIds: [],
        tagNames: [],
        taskId: "7001",
        userId: "6001",
        userGroupIds: [],
        workspaceId: "1001",
        entryCount: 0,
        linkedId: "clock-entry-02",
        isIncluded: false,
        memberOf: "timeEntries",
      },
      "8003": {
        id: "8003",
        description: "This is a test entry (03)",
        isBillable: false,
        start: "2019-06-23T14:30:00.000Z",
        end: "2019-06-24T04:30:00.000Z",
        year: 2019,
        isActive: false,
        clientId: "3001",
        projectId: "2001",
        tagIds: ["4003"],
        tagNames: ["tag-c"],
        taskId: "7002",
        userId: "6001",
        userGroupIds: [],
        workspaceId: "1001",
        entryCount: 0,
        linkedId: "clock-entry-03",
        isIncluded: false,
        memberOf: "timeEntries",
      },
      "8004": {
        id: "8004",
        description: "This is a test entry (04)",
        isBillable: false,
        start: "2019-06-23T14:00:20.000Z",
        end: "2019-06-23T17:05:20.000Z",
        year: 2019,
        isActive: false,
        clientId: "3002",
        projectId: "2002",
        tagIds: [],
        tagNames: [],
        taskId: null,
        userId: "6001",
        userGroupIds: [],
        workspaceId: "1001",
        entryCount: 0,
        linkedId: "clock-entry-04",
        isIncluded: false,
        memberOf: "timeEntries",
      },
      "8005": {
        id: "8005",
        description: "This is a test entry (05)",
        isBillable: false,
        start: "2019-06-22T14:00:19.000Z",
        end: "2019-06-22T19:15:19.000Z",
        year: 2019,
        isActive: false,
        clientId: "3002",
        projectId: "2002",
        tagIds: [],
        tagNames: [],
        taskId: null,
        userId: "6001",
        userGroupIds: [],
        workspaceId: "1001",
        entryCount: 0,
        linkedId: "clock-entry-05",
        isIncluded: false,
        memberOf: "timeEntries",
      },
      "8006": {
        id: "8006",
        description: "This is a test entry (06)",
        isBillable: false,
        start: "2019-06-21T20:45:57.000Z",
        end: "2019-06-21T21:50:57.000Z",
        year: 2019,
        isActive: false,
        clientId: "3002",
        projectId: "2002",
        tagIds: [],
        tagNames: [],
        taskId: "7003",
        userId: "6001",
        userGroupIds: [],
        workspaceId: "1001",
        entryCount: 0,
        linkedId: "clock-entry-06",
        isIncluded: false,
        memberOf: "timeEntries",
      },
      "8007": {
        id: "8007",
        description: "This is a test entry (07)",
        isBillable: false,
        start: "2019-05-02T10:00:00.000Z",
        end: "2019-05-02T12:00:00.000Z",
        year: 2019,
        isActive: false,
        clientId: null,
        projectId: "2003",
        tagIds: [],
        tagNames: [],
        taskId: "7004",
        userId: "6001",
        userGroupIds: [],
        workspaceId: "1001",
        entryCount: 0,
        linkedId: "clock-entry-07",
        isIncluded: false,
        memberOf: "timeEntries",
      },
      "8008": {
        id: "8008",
        description: "This is a test entry (08)",
        isBillable: false,
        start: "2019-05-01T20:00:00.000Z",
        end: "2019-05-01T21:00:00.000Z",
        year: 2019,
        isActive: false,
        clientId: null,
        projectId: "2003",
        tagIds: [],
        tagNames: [],
        taskId: null,
        userId: "6001",
        userGroupIds: [],
        workspaceId: "1001",
        entryCount: 0,
        linkedId: "clock-entry-08",
        isIncluded: false,
        memberOf: "timeEntries",
      },
      "8009": {
        id: "8009",
        description: "This is a test entry (09)",
        isBillable: false,
        start: "2018-06-25T18:00:00.000Z",
        end: "2018-06-25T23:00:00.000Z",
        year: 2018,
        isActive: false,
        clientId: null,
        projectId: "2003",
        tagIds: [],
        tagNames: [],
        taskId: null,
        userId: "6001",
        userGroupIds: [],
        workspaceId: "1001",
        entryCount: 0,
        linkedId: "clock-entry-09",
        isIncluded: false,
        memberOf: "timeEntries",
      },
      "8010": {
        id: "8010",
        description: "This is a test entry (10)",
        isBillable: false,
        start: "2018-06-24T14:00:00.000Z",
        end: "2018-06-24T22:00:00.000Z",
        year: 2018,
        isActive: false,
        clientId: null,
        projectId: "2004",
        tagIds: [],
        tagNames: [],
        taskId: "7005",
        userId: "6001",
        userGroupIds: [],
        workspaceId: "1001",
        entryCount: 0,
        linkedId: "clock-entry-10",
        isIncluded: false,
        memberOf: "timeEntries",
      },
      "8011": {
        id: "8011",
        description: "This is a test entry (11)",
        isBillable: false,
        start: "2018-06-23T14:30:00.000Z",
        end: "2018-06-24T04:30:00.000Z",
        year: 2018,
        isActive: false,
        clientId: null,
        projectId: "2004",
        tagIds: [],
        tagNames: [],
        taskId: "7005",
        userId: "6001",
        userGroupIds: [],
        workspaceId: "1001",
        entryCount: 0,
        linkedId: "clock-entry-11",
        isIncluded: false,
        memberOf: "timeEntries",
      },
      "8012": {
        id: "8012",
        description: "This is a test entry (12)",
        isBillable: false,
        start: "2018-06-23T14:00:20.000Z",
        end: "2018-06-23T17:05:20.000Z",
        year: 2018,
        isActive: false,
        clientId: null,
        projectId: "2004",
        tagIds: [],
        tagNames: [],
        taskId: "7005",
        userId: "6001",
        userGroupIds: [],
        workspaceId: "1001",
        entryCount: 0,
        linkedId: "clock-entry-12",
        isIncluded: false,
        memberOf: "timeEntries",
      },
      "8013": {
        id: "8013",
        description: "This is a test entry (13)",
        isBillable: false,
        start: "2018-06-22T14:00:19.000Z",
        end: "2018-06-22T19:15:19.000Z",
        year: 2018,
        isActive: false,
        clientId: null,
        projectId: "2005",
        tagIds: [],
        tagNames: [],
        taskId: null,
        userId: "6001",
        userGroupIds: [],
        workspaceId: "1001",
        entryCount: 0,
        linkedId: "clock-entry-13",
        isIncluded: false,
        memberOf: "timeEntries",
      },
      "8014": {
        id: "8014",
        description: "This is a test entry (14)",
        isBillable: false,
        start: "2018-06-21T20:45:57.000Z",
        end: "2018-06-21T21:50:57.000Z",
        year: 2018,
        isActive: false,
        clientId: null,
        projectId: "2005",
        tagIds: [],
        tagNames: [],
        taskId: null,
        userId: "6001",
        userGroupIds: [],
        workspaceId: "1001",
        entryCount: 0,
        linkedId: "clock-entry-14",
        isIncluded: false,
        memberOf: "timeEntries",
      },
      "8015": {
        id: "8015",
        description: "This is a test entry (15)",
        isBillable: false,
        start: "2017-06-25T18:00:00.000Z",
        end: "2017-06-25T23:00:00.000Z",
        year: 2017,
        isActive: false,
        clientId: null,
        projectId: "2005",
        tagIds: [],
        tagNames: [],
        taskId: null,
        userId: "6001",
        userGroupIds: [],
        workspaceId: "1001",
        entryCount: 0,
        linkedId: "clock-entry-15",
        isIncluded: false,
        memberOf: "timeEntries",
      },
      "8016": {
        id: "8016",
        description: "This is a test entry (16)",
        isBillable: false,
        start: "2017-06-24T14:00:00.000Z",
        end: "2017-06-24T22:00:00.000Z",
        year: 2017,
        isActive: false,
        clientId: null,
        projectId: "2005",
        tagIds: [],
        tagNames: [],
        taskId: null,
        userId: "6001",
        userGroupIds: [],
        workspaceId: "1001",
        entryCount: 0,
        linkedId: "clock-entry-16",
        isIncluded: false,
        memberOf: "timeEntries",
      },
      "8017": {
        id: "8017",
        description: "This is a test entry (17)",
        isBillable: false,
        start: "2017-06-23T14:30:00.000Z",
        end: "2017-06-24T04:30:00.000Z",
        year: 2017,
        isActive: false,
        clientId: null,
        projectId: "2006",
        tagIds: [],
        tagNames: [],
        taskId: null,
        userId: "6001",
        userGroupIds: [],
        workspaceId: "1001",
        entryCount: 0,
        linkedId: "clock-entry-17",
        isIncluded: false,
        memberOf: "timeEntries",
      },
      "8018": {
        id: "8018",
        description: "This is a test entry (18)",
        isBillable: false,
        start: "2017-06-23T14:00:20.000Z",
        end: "2017-06-23T17:05:20.000Z",
        year: 2017,
        isActive: false,
        clientId: null,
        projectId: "2006",
        tagIds: [],
        tagNames: [],
        taskId: null,
        userId: "6001",
        userGroupIds: [],
        workspaceId: "1001",
        entryCount: 0,
        linkedId: "clock-entry-18",
        isIncluded: false,
        memberOf: "timeEntries",
      },
      "8019": {
        id: "8019",
        description: "This is a test entry (19)",
        isBillable: false,
        start: "2017-06-22T14:00:19.000Z",
        end: "2017-06-22T19:15:19.000Z",
        year: 2017,
        isActive: false,
        clientId: null,
        projectId: "2006",
        tagIds: [],
        tagNames: [],
        taskId: null,
        userId: "6001",
        userGroupIds: [],
        workspaceId: "1001",
        entryCount: 0,
        linkedId: "clock-entry-19",
        isIncluded: false,
        memberOf: "timeEntries",
      },
      "8020": {
        id: "8020",
        description: "This is a test entry (20)",
        isBillable: false,
        start: "2017-06-21T20:45:57.000Z",
        end: "2017-06-21T21:50:57.000Z",
        year: 2017,
        isActive: false,
        clientId: null,
        projectId: "2006",
        tagIds: [],
        tagNames: [],
        taskId: null,
        userId: "6001",
        userGroupIds: [],
        workspaceId: "1001",
        entryCount: 0,
        linkedId: "clock-entry-20",
        isIncluded: false,
        memberOf: "timeEntries",
      },
    },
    target: {
      "clock-entry-20": {
        id: "clock-entry-20",
        description: "This is a test entry (20)",
        isBillable: false,
        start: "2017-06-21T20:45:57.000Z",
        end: "2017-06-21T21:50:57.000Z",
        year: 2017,
        isActive: false,
        clientId: "",
        projectId: "clock-project-06",
        tagIds: [],
        tagNames: [],
        taskId: null,
        userId: "clock-user-01",
        userGroupIds: [],
        workspaceId: "clock-workspace-01",
        entryCount: 0,
        linkedId: "8020",
        isIncluded: true,
        memberOf: "timeEntries",
      },
      "clock-entry-19": {
        id: "clock-entry-19",
        description: "This is a test entry (19)",
        isBillable: false,
        start: "2017-06-22T14:00:19.000Z",
        end: "2017-06-22T19:15:19.000Z",
        year: 2017,
        isActive: false,
        clientId: "",
        projectId: "clock-project-06",
        tagIds: [],
        tagNames: [],
        taskId: null,
        userId: "clock-user-01",
        userGroupIds: [],
        workspaceId: "clock-workspace-01",
        entryCount: 0,
        linkedId: "8019",
        isIncluded: true,
        memberOf: "timeEntries",
      },
      "clock-entry-18": {
        id: "clock-entry-18",
        description: "This is a test entry (18)",
        isBillable: false,
        start: "2017-06-23T14:00:20.000Z",
        end: "2017-06-23T17:05:20.000Z",
        year: 2017,
        isActive: false,
        clientId: "",
        projectId: "clock-project-06",
        tagIds: [],
        tagNames: [],
        taskId: null,
        userId: "clock-user-01",
        userGroupIds: [],
        workspaceId: "clock-workspace-01",
        entryCount: 0,
        linkedId: "8018",
        isIncluded: true,
        memberOf: "timeEntries",
      },
      "clock-entry-17": {
        id: "clock-entry-17",
        description: "This is a test entry (17)",
        isBillable: false,
        start: "2017-06-23T14:30:00.000Z",
        end: "2017-06-24T04:30:00.000Z",
        year: 2017,
        isActive: false,
        clientId: "",
        projectId: "clock-project-06",
        tagIds: [],
        tagNames: [],
        taskId: null,
        userId: "clock-user-01",
        userGroupIds: [],
        workspaceId: "clock-workspace-01",
        entryCount: 0,
        linkedId: "8017",
        isIncluded: true,
        memberOf: "timeEntries",
      },
      "clock-entry-16": {
        id: "clock-entry-16",
        description: "This is a test entry (16)",
        isBillable: false,
        start: "2017-06-24T14:00:00.000Z",
        end: "2017-06-24T22:00:00.000Z",
        year: 2017,
        isActive: false,
        clientId: "",
        projectId: "clock-project-05",
        tagIds: [],
        tagNames: [],
        taskId: null,
        userId: "clock-user-01",
        userGroupIds: [],
        workspaceId: "clock-workspace-01",
        entryCount: 0,
        linkedId: "8016",
        isIncluded: true,
        memberOf: "timeEntries",
      },
      "clock-entry-15": {
        id: "clock-entry-15",
        description: "This is a test entry (15)",
        isBillable: false,
        start: "2017-06-25T18:00:00.000Z",
        end: "2017-06-25T23:00:00.000Z",
        year: 2017,
        isActive: false,
        clientId: "",
        projectId: "clock-project-05",
        tagIds: [],
        tagNames: [],
        taskId: null,
        userId: "clock-user-01",
        userGroupIds: [],
        workspaceId: "clock-workspace-01",
        entryCount: 0,
        linkedId: "8015",
        isIncluded: true,
        memberOf: "timeEntries",
      },
      "clock-entry-14": {
        id: "clock-entry-14",
        description: "This is a test entry (14)",
        isBillable: false,
        start: "2018-06-21T20:45:57.000Z",
        end: "2018-06-21T21:50:57.000Z",
        year: 2018,
        isActive: false,
        clientId: "",
        projectId: "clock-project-05",
        tagIds: [],
        tagNames: [],
        taskId: null,
        userId: "clock-user-01",
        userGroupIds: [],
        workspaceId: "clock-workspace-01",
        entryCount: 0,
        linkedId: "8014",
        isIncluded: true,
        memberOf: "timeEntries",
      },
      "clock-entry-13": {
        id: "clock-entry-13",
        description: "This is a test entry (13)",
        isBillable: false,
        start: "2018-06-22T14:00:19.000Z",
        end: "2018-06-22T19:15:19.000Z",
        year: 2018,
        isActive: false,
        clientId: "",
        projectId: "clock-project-05",
        tagIds: [],
        tagNames: [],
        taskId: null,
        userId: "clock-user-01",
        userGroupIds: [],
        workspaceId: "clock-workspace-01",
        entryCount: 0,
        linkedId: "8013",
        isIncluded: true,
        memberOf: "timeEntries",
      },
      "clock-entry-12": {
        id: "clock-entry-12",
        description: "This is a test entry (12)",
        isBillable: false,
        start: "2018-06-23T14:00:20.000Z",
        end: "2018-06-23T17:05:20.000Z",
        year: 2018,
        isActive: false,
        clientId: "",
        projectId: "clock-project-04",
        tagIds: [],
        tagNames: [],
        taskId: null,
        userId: "clock-user-01",
        userGroupIds: [],
        workspaceId: "clock-workspace-01",
        entryCount: 0,
        linkedId: "8012",
        isIncluded: true,
        memberOf: "timeEntries",
      },
      "clock-entry-11": {
        id: "clock-entry-11",
        description: "This is a test entry (11)",
        isBillable: false,
        start: "2018-06-23T14:30:00.000Z",
        end: "2018-06-24T04:30:00.000Z",
        year: 2018,
        isActive: false,
        clientId: "",
        projectId: "clock-project-04",
        tagIds: [],
        tagNames: [],
        taskId: null,
        userId: "clock-user-01",
        userGroupIds: [],
        workspaceId: "clock-workspace-01",
        entryCount: 0,
        linkedId: "8011",
        isIncluded: true,
        memberOf: "timeEntries",
      },
      "clock-entry-10": {
        id: "clock-entry-10",
        description: "This is a test entry (10)",
        isBillable: false,
        start: "2018-06-24T14:00:00.000Z",
        end: "2018-06-24T22:00:00.000Z",
        year: 2018,
        isActive: false,
        clientId: "",
        projectId: "clock-project-04",
        tagIds: [],
        tagNames: [],
        taskId: null,
        userId: "clock-user-01",
        userGroupIds: [],
        workspaceId: "clock-workspace-01",
        entryCount: 0,
        linkedId: "8010",
        isIncluded: true,
        memberOf: "timeEntries",
      },
      "clock-entry-09": {
        id: "clock-entry-09",
        description: "This is a test entry (09)",
        isBillable: false,
        start: "2018-06-25T18:00:00.000Z",
        end: "2018-06-25T23:00:00.000Z",
        year: 2018,
        isActive: false,
        clientId: "",
        projectId: "clock-project-03",
        tagIds: ["clock-tag-03", "clock-tag-04", "clock-tag-05"],
        tagNames: ["tag-c", "tag-d", "tag-e"],
        taskId: null,
        userId: "clock-user-01",
        userGroupIds: [],
        workspaceId: "clock-workspace-01",
        entryCount: 0,
        linkedId: "8009",
        isIncluded: true,
        memberOf: "timeEntries",
      },
      "clock-entry-08": {
        id: "clock-entry-08",
        description: "This is a test entry (08)",
        isBillable: false,
        start: "2019-05-01T20:00:00.000Z",
        end: "2019-05-01T21:00:00.000Z",
        year: 2019,
        isActive: false,
        clientId: "",
        projectId: "clock-project-03",
        tagIds: [],
        tagNames: [],
        taskId: null,
        userId: "clock-user-01",
        userGroupIds: [],
        workspaceId: "clock-workspace-01",
        entryCount: 0,
        linkedId: "8008",
        isIncluded: true,
        memberOf: "timeEntries",
      },
      "clock-entry-07": {
        id: "clock-entry-07",
        description: "This is a test entry (07)",
        isBillable: false,
        start: "2019-05-02T10:00:00.000Z",
        end: "2019-05-02T12:00:00.000Z",
        year: 2019,
        isActive: false,
        clientId: "",
        projectId: "clock-project-03",
        tagIds: [],
        tagNames: [],
        taskId: null,
        userId: "clock-user-01",
        userGroupIds: [],
        workspaceId: "clock-workspace-01",
        entryCount: 0,
        linkedId: "8007",
        isIncluded: true,
        memberOf: "timeEntries",
      },
      "clock-entry-06": {
        id: "clock-entry-06",
        description: "This is a test entry (06)",
        isBillable: false,
        start: "2019-06-21T20:45:57.000Z",
        end: "2019-06-21T21:50:57.000Z",
        year: 2019,
        isActive: false,
        clientId: "clock-client-02",
        projectId: "clock-project-02",
        tagIds: ["clock-tag-03", "clock-tag-04"],
        tagNames: ["tag-c", "tag-d"],
        taskId: "clock-task-05",
        userId: "clock-user-01",
        userGroupIds: [],
        workspaceId: "clock-workspace-01",
        entryCount: 0,
        linkedId: "8006",
        isIncluded: true,
        memberOf: "timeEntries",
      },
      "clock-entry-05": {
        id: "clock-entry-05",
        description: "This is a test entry (05)",
        isBillable: false,
        start: "2019-06-22T14:00:19.000Z",
        end: "2019-06-22T19:15:19.000Z",
        year: 2019,
        isActive: false,
        clientId: "clock-client-02",
        projectId: "clock-project-02",
        tagIds: [],
        tagNames: [],
        taskId: "clock-task-04",
        userId: "clock-user-01",
        userGroupIds: [],
        workspaceId: "clock-workspace-01",
        entryCount: 0,
        linkedId: "8005",
        isIncluded: true,
        memberOf: "timeEntries",
      },
      "clock-entry-04": {
        id: "clock-entry-04",
        description: "This is a test entry (04)",
        isBillable: false,
        start: "2019-06-23T14:00:20.000Z",
        end: "2019-06-23T17:05:20.000Z",
        year: 2019,
        isActive: false,
        clientId: "clock-client-02",
        projectId: "clock-project-02",
        tagIds: ["clock-tag-02", "clock-tag-03"],
        tagNames: ["tag-b", "tag-c"],
        taskId: "clock-task-04",
        userId: "clock-user-01",
        userGroupIds: [],
        workspaceId: "clock-workspace-01",
        entryCount: 0,
        linkedId: "8004",
        isIncluded: true,
        memberOf: "timeEntries",
      },
      "clock-entry-03": {
        id: "clock-entry-03",
        description: "This is a test entry (03)",
        isBillable: false,
        start: "2019-06-23T14:30:00.000Z",
        end: "2019-06-24T04:30:00.000Z",
        year: 2019,
        isActive: false,
        clientId: "clock-client-01",
        projectId: "clock-project-01",
        tagIds: ["clock-tag-01"],
        tagNames: ["tag-a"],
        taskId: "clock-task-03",
        userId: "clock-user-01",
        userGroupIds: [],
        workspaceId: "clock-workspace-01",
        entryCount: 0,
        linkedId: "8003",
        isIncluded: true,
        memberOf: "timeEntries",
      },
      "clock-entry-02": {
        id: "clock-entry-02",
        description: "This is a test entry (02)",
        isBillable: false,
        start: "2019-06-24T14:00:00.000Z",
        end: "2019-06-24T22:00:00.000Z",
        year: 2019,
        isActive: false,
        clientId: "clock-client-01",
        projectId: "clock-project-01",
        tagIds: [],
        tagNames: [],
        taskId: "clock-task-02",
        userId: "clock-user-01",
        userGroupIds: [],
        workspaceId: "clock-workspace-01",
        entryCount: 0,
        linkedId: "8002",
        isIncluded: true,
        memberOf: "timeEntries",
      },
      "clock-entry-01": {
        id: "clock-entry-01",
        description: "This is a test entry (01)",
        isBillable: false,
        start: "2019-06-25T18:00:00.000Z",
        end: "2019-06-25T23:00:00.000Z",
        year: 2019,
        isActive: false,
        clientId: "clock-client-01",
        projectId: "clock-project-01",
        tagIds: ["clock-tag-01", "clock-tag-02"],
        tagNames: ["tag-a", "tag-b"],
        taskId: "clock-task-01",
        userId: "clock-user-01",
        userGroupIds: [],
        workspaceId: "clock-workspace-01",
        entryCount: 0,
        linkedId: "8001",
        isIncluded: true,
        memberOf: "timeEntries",
      },
    },
    isFetching: false,
  },
  userGroups: {
    source: {
      "5001": {
        id: "5001",
        name: "Test Group A",
        userIds: [],
        workspaceId: "1001",
        entryCount: 0,
        linkedId: "clock-user-group-02",
        isIncluded: false,
        memberOf: "userGroups",
      },
      "5002": {
        id: "5002",
        name: "Test Group B",
        userIds: [],
        workspaceId: "1001",
        entryCount: 0,
        linkedId: null,
        isIncluded: true,
        memberOf: "userGroups",
      },
    },
    target: {
      "clock-user-group-01": {
        id: "clock-user-group-01",
        name: "Admins",
        userIds: ["clock-user-01"],
        workspaceId: "clock-workspace-01",
        entryCount: 0,
        linkedId: null,
        isIncluded: true,
        memberOf: "userGroups",
      },
      "clock-user-group-02": {
        id: "clock-user-group-02",
        name: "Test Group A",
        userIds: [],
        workspaceId: "clock-workspace-01",
        entryCount: 0,
        linkedId: "5001",
        isIncluded: false,
        memberOf: "userGroups",
      },
    },
    isFetching: false,
  },
  users: {
    source: {
      "6001": {
        id: "6001",
        name: "John Test",
        email: "test-user@test.com",
        isAdmin: null,
        isActive: true,
        userGroupIds: [],
        workspaceId: "1001",
        entryCount: 0,
        linkedId: "clock-user-01",
        isIncluded: false,
        memberOf: "users",
      },
    },
    target: {
      "clock-user-01": {
        id: "clock-user-01",
        name: "John Test",
        email: "test-user@test.com",
        isAdmin: null,
        isActive: true,
        userGroupIds: [],
        workspaceId: "clock-workspace-01",
        entryCount: 0,
        linkedId: "6001",
        isIncluded: false,
        memberOf: "users",
      },
    },
    isFetching: false,
  },
  workspaces: {
    source: {
      "1001": {
        id: "1001",
        name: "Test Workspace",
        userIds: ["6001"],
        isAdmin: true,
        workspaceId: "1001",
        entryCount: 20,
        linkedId: "clock-workspace-01",
        isIncluded: true,
        memberOf: "workspaces",
      },
    },
    target: {
      "clock-workspace-01": {
        id: "clock-workspace-01",
        name: "Test Workspace",
        userIds: [],
        isAdmin: true,
        workspaceId: "clock-workspace-01",
        entryCount: 0,
        linkedId: "1001",
        isIncluded: true,
        memberOf: "workspaces",
      },
    },
    activeWorkspaceId: "1001",
    isFetching: false,
  },
} as any;
