// @ts-ignore
const responses = {
  clients: {
    apiFetchClockifyClients: {
      url: '/clockify/api/workspaces/{workspaceId}/clients/',
      method: 'GET',
      response: [
        {
          id: 'testClientA',
          name: 'Test Client A',
          workspaceId: 'testWorkspaceA',
        },
        {
          id: 'testClientB',
          name: 'Test Client B',
          workspaceId: 'testWorkspaceA',
        },
      ],
    },
    apiFetchTogglClients: {
      url: '/toggl/api/workspaces/{workspaceId}/clients',
      method: 'GET',
      response: [
        {
          id: 300001,
          wid: 200001,
          name: 'Test Client A',
          at: '2017-08-01T20:39:41+00:00',
        },
        {
          id: 300002,
          wid: 200001,
          name: 'Test Client B',
          at: '2017-06-27T21:03:05+00:00',
        },
      ],
    },
  },
  projects: {
    apiFetchClockifyProjects: {
      url: '/clockify/api/workspaces/{workspaceId}/projects/',
      method: 'GET',
      response: [
        {
          id: 'testProjectA',
          name: 'Project One',
          hourlyRate: null as any,
          clientId: '',
          client: null as any,
          workspaceId: 'testWorkspaceA',
          billable: true,
          memberships: [
            {
              userId: 'userId',
              hourlyRate: null as any,
              membershipType: 'PROJECT',
              membershipStatus: 'ACTIVE',
              target: 'targetA',
            },
          ],
          color: '#f44336',
          estimate: {
            estimate: 'PT0S',
            type: 'AUTO',
          },
          archived: false,
          tasks: [] as any,
          public: false,
        },
        {
          id: 'testProjectB',
          name: 'Project Two',
          hourlyRate: null,
          clientId: '',
          client: null,
          workspaceId: 'testWorkspaceA',
          billable: true,
          memberships: [
            {
              userId: 'userId',
              hourlyRate: null,
              membershipType: 'PROJECT',
              membershipStatus: 'ACTIVE',
              target: 'targetB',
            },
          ],
          color: '#9ba8b0',
          estimate: {
            estimate: 'PT0S',
            type: 'AUTO',
          },
          archived: false,
          tasks: [],
          public: false,
        },
      ],
    },
    apiFetchTogglProjects: {
      url: '/toggl/api/workspaces/{workspaceId}/projects',
      method: 'GET',
      response: [
        {
          id: 400001,
          wid: 200001,
          cid: 300001,
          name: 'Test Project A',
          billable: false,
          is_private: true,
          active: true,
          template: false,
          at: '2017-08-16T18:29:51+00:00',
          created_at: '2017-08-16T18:29:46+00:00',
          color: '11',
          auto_estimates: false,
          actual_hours: 129,
          hex_color: '#205500',
        },
        {
          id: 400002,
          wid: 200001,
          cid: 300001,
          name: 'Test Project B',
          billable: false,
          is_private: true,
          active: true,
          template: false,
          at: '2018-01-23T21:44:49+00:00',
          created_at: '2018-01-23T21:44:36+00:00',
          color: '8',
          auto_estimates: false,
          actual_hours: 124,
          hex_color: '#3750b5',
        },
      ],
    },
  },
  tags: {
    apiFetchClockifyTags: {
      url: '/clockify/api/workspaces/{workspaceId}/tags/',
      method: 'GET',
      response: [
        {
          id: 'testTagA',
          name: 'Tag One',
          workspaceId: 'testWorkspaceA',
        },
        {
          id: 'testTagB',
          name: 'Tag Two',
          workspaceId: 'testWorkspaceA',
        },
      ],
    },
    apiFetchTogglTags: {
      url: '/toggl/api/workspaces/{workspaceId}/tags',
      method: 'GET',
      response: [
        {
          id: 500001,
          wid: 200001,
          name: 'tag-one',
          at: '2018-09-10T18:02:08+00:00',
        },
        {
          id: 500002,
          wid: 200001,
          name: 'tag-two',
          at: '2017-12-06T20:47:13+00:00',
        },
      ],
    },
  },
  tasks: {
    apiFetchClockifyTasks: {
      url: '/clockify/api/workspaces/{workspaceId}/tasks/',
      method: 'GET',
      response: [
        {
          id: 'testTaskA',
          name: 'Test Task A',
          projectId: 'testProjectA',
          assigneeId: 'userId',
          estimate: 'PT30M',
          status: 'ACTIVE',
        },
        {
          id: 'testTaskB',
          name: 'Test Task A',
          projectId: 'testProjectA',
          assigneeId: 'userId',
          estimate: 'PT120H',
          status: 'ACTIVE',
        },
      ],
    },
    apiFetchTogglTasks: {
      url: '/toggl/api/workspaces/{workspaceId}/tasks',
      method: 'GET',
      response: [
        {
          name: 'Test Task A',
          id: 700001,
          wid: 200001,
          pid: 400001,
          uid: 100001,
          active: true,
          at: '2013-03-06T09:15:51+00:00',
          estimated_seconds: 7200,
        },
        {
          name: 'Test Task B',
          id: 700002,
          wid: 200001,
          pid: 400001,
          active: true,
          at: '2013-03-06T09:15:59+00:00',
          estimated_seconds: 0,
        },
      ],
    },
  },
  timeEntries: {
    apiFetchClockifyTimeEntries: {
      url:
        '/clockify/api/workspaces/{workspaceId}/timeEntries/user/{userId}/entriesInRange',
      body: {
        start: '2018-01-01T00:00:00.000Z',
        end: '2018-12-31T23:59:59.999Z',
      },
      method: 'POST',
      response: [
        {
          id: 'testTimeEntryA',
          description: 'Description of time entry A.',
          tags: null as any,
          user: {
            id: 'userId',
            email: 'test@test.com',
            name: 'John User',
            memberships: [
              {
                userId: 'userId',
                hourlyRate: null as any,
                membershipType: 'WORKSPACE',
                membershipStatus: 'ACTIVE',
                target: 'targetA',
              },
            ],
            profilePicture:
              'https://s3.eu-central-1.amazonaws.com/clockify/no-user-image.png',
            activeWorkspace: 'testWorkspaceA',
            defaultWorkspace: 'testWorkspaceA',
            settings: {
              weekStart: 'MONDAY',
              timeZone: 'America/Chicago',
              timeFormat: 'HOUR12',
              dateFormat: 'MM/DD/YYYY',
              sendNewsletter: true,
              weeklyUpdates: true,
              longRunning: false,
              summaryReportSettings: {
                group: 'Project',
                subgroup: 'Time Entry',
              },
              isCompactViewOn: false,
              dashboardSelection: 'ME',
              timeTrackingManual: false,
            },
            status: 'ACTIVE',
          },
          billable: false,
          task: {
            id: 'testTaskA',
            name: 'Test Task A',
            projectId: 'testProjectA',
            assigneeId: 'userId',
            estimate: 'PT30M',
            status: 'ACTIVE',
          },
          project: {
            id: 'testProjectA',
            name: 'Test Project A',
            hourlyRate: null as any,
            clientId: 'testClientA',
            workspaceId: 'testWorkspaceA',
            billable: false,
            memberships: [
              {
                userId: 'userId',
                hourlyRate: null as any,
                membershipType: 'PROJECT',
                membershipStatus: 'ACTIVE',
                target: 'testTargetA',
              },
            ],
            color: '#03a9f4',
            estimate: {
              estimate: 'PT1168H30M',
              type: 'AUTO',
            },
            archived: false,
            duration: 'PT288H5M',
            clientName: 'Test Client A',
            public: false,
          },
          timeInterval: {
            start: '2018-10-09T21:00:00Z',
            end: '2018-10-09T21:30:00Z',
            duration: 'PT30M',
          },
          workspaceId: 'testWorkspaceA',
          totalBillable: null as any,
          hourlyRate: null as any,
          isLocked: false,
          projectId: 'testProjectA',
        },
        {
          id: 'testTimeEntryB',
          description: 'Description of time entry B.',
          tags: null,
          user: {
            id: 'userId',
            email: 'test@test.com',
            name: 'John User',
            memberships: [
              {
                userId: 'userId',
                hourlyRate: null as any,
                membershipType: 'WORKSPACE',
                membershipStatus: 'ACTIVE',
                target: 'targetA',
              },
            ],
            profilePicture:
              'https://s3.eu-central-1.amazonaws.com/clockify/no-user-image.png',
            activeWorkspace: 'testWorkspaceA',
            defaultWorkspace: 'testWorkspaceA',
            settings: {
              weekStart: 'MONDAY',
              timeZone: 'America/Chicago',
              timeFormat: 'HOUR12',
              dateFormat: 'MM/DD/YYYY',
              sendNewsletter: true,
              weeklyUpdates: true,
              longRunning: false,
              summaryReportSettings: {
                group: 'Project',
                subgroup: 'Time Entry',
              },
              isCompactViewOn: false,
              dashboardSelection: 'ME',
              timeTrackingManual: false,
            },
            status: 'ACTIVE',
          },
          billable: false,
          task: {
            id: 'testTaskA',
            name: 'Test Task A',
            projectId: 'testProjectA',
            assigneeId: 'userId',
            estimate: 'PT30M',
            status: 'ACTIVE',
          },
          project: {
            id: 'testProjectA',
            name: 'Test Project A',
            hourlyRate: null as any,
            clientId: 'testClientA',
            workspaceId: 'testWorkspaceA',
            billable: false,
            memberships: [
              {
                userId: 'userId',
                hourlyRate: null as any,
                membershipType: 'PROJECT',
                membershipStatus: 'ACTIVE',
                target: 'testTargetA',
              },
            ],
            color: '#03a9f4',
            estimate: {
              estimate: 'PT1168H30M',
              type: 'AUTO',
            },
            archived: false,
            duration: 'PT288H5M',
            clientName: 'Test Client A',
            public: false,
          },
          timeInterval: {
            start: '2018-10-09T21:00:00Z',
            end: '2018-10-09T21:30:00Z',
            duration: 'PT30M',
          },
          workspaceId: 'testWorkspaceA',
          totalBillable: null as any,
          hourlyRate: null as any,
          isLocked: false,
          projectId: 'testProjectA',
        },
      ],
    },
    apiFetchTogglTimeEntries: {
      url:
        '/toggl/reports/details?workspace_id={workspaceId}&since={date}&until={date}&user_agent={email}',
      method: 'GET',
      response: {
        total_grand: 2985300000,
        total_billable: null as any,
        total_currencies: [
          {
            currency: null as any,
            amount: null as any,
          },
        ],
        total_count: 300,
        per_page: 50,
        data: [
          {
            id: 600001,
            pid: 400001,
            tid: null as any,
            uid: 100001,
            description: 'Description for time entry A.',
            start: '2018-08-30T13:00:38-05:00',
            end: '2018-08-30T15:00:38-05:00',
            updated: '2018-09-10T13:02:09-05:00',
            dur: 7200000,
            user: 'John User',
            use_stop: true,
            client: 'Test Client A',
            project: 'Test Project A',
            project_color: '0',
            project_hex_color: '#3750b5',
            task: null as any,
            billable: null as any,
            is_billable: false,
            cur: null as any,
            tags: ['tag-one'],
          },
          {
            id: 600002,
            pid: 400001,
            tid: null,
            uid: 100001,
            description: 'Description for time entry B.',
            start: '2018-08-30T09:30:19-05:00',
            end: '2018-08-30T12:00:19-05:00',
            updated: '2018-09-10T13:02:09-05:00',
            dur: 9000000,
            user: 'John User',
            use_stop: true,
            client: 'Test Client A',
            project: 'Test Project A',
            project_color: '0',
            project_hex_color: '#3750b5',
            task: null,
            billable: null,
            is_billable: false,
            cur: null,
            tags: ['tag-two'],
          },
        ],
      },
    },
  },
  user: {
    apiFetchClockifyUserDetails: {
      url: '/clockify/api/users/{userId}',
      method: 'GET',
      response: {
        id: 'userId',
        email: 'test@test.com',
        name: 'Testing',
        memberships: [
          {
            userId: 'userId',
            hourlyRate: null as any,
            membershipType: 'WORKSPACE',
            membershipStatus: 'ACTIVE',
            target: 'targetId',
          },
        ],
        profilePicture:
          'https://s3.eu-central-1.amazonaws.com/clockify/no-user-image.png',
        activeWorkspace: 'testWorkspaceA',
        defaultWorkspace: 'testWorkspaceA',
        settings: {
          weekStart: 'MONDAY',
          timeZone: 'America/Chicago',
          timeFormat: 'HOUR12',
          dateFormat: 'MM/DD/YYYY',
          sendNewsletter: true,
          weeklyUpdates: false,
          longRunning: false,
          summaryReportSettings: {
            group: 'Project',
            subgroup: 'Time Entry',
          },
          isCompactViewOn: false,
          dashboardSelection: 'ME',
          timeTrackingManual: false,
        },
        status: 'ACTIVE',
      },
    },
    apiFetchTogglUserDetails: {
      url: '/toggl/api/me',
      method: 'GET',
      response: {
        since: 1545596501,
        data: {
          id: 100001,
          api_token: 'testApiToken',
          default_wid: 200001,
          email: 'test@test.com',
          fullname: 'John User',
          jquery_timeofday_format: 'h:i A',
          jquery_date_format: 'm/d/Y',
          timeofday_format: 'h:mm A',
          date_format: 'MM/DD/YYYY',
          store_start_and_stop_time: false,
          beginning_of_week: 0,
          language: 'en_US',
          image_url: 'https://user.url',
          sidebar_piechart: true,
          at: '2017-09-10T21:02:53+00:00',
          created_at: '2016-11-01T18:05:24+00:00',
          retention: 9,
          record_timeline: true,
          render_timeline: true,
          timeline_enabled: true,
          timeline_experiment: false,
          new_blog_post: {},
          should_upgrade: true,
          achievements_enabled: true,
          timezone: 'America/Chicago',
          openid_enabled: true,
          openid_email: 'test@test.com',
          send_product_emails: false,
          send_weekly_report: false,
          send_timer_notifications: false,
          last_blog_entry: '',
          invitation: {},
          workspaces: [
            {
              id: 200001,
              name: 'Workspace A',
              profile: 0,
              premium: false,
              admin: true,
              default_hourly_rate: 0,
              default_currency: 'USD',
              only_admins_may_create_projects: false,
              only_admins_see_billable_rates: false,
              only_admins_see_team_dashboard: false,
              projects_billable_by_default: true,
              rounding: 0,
              rounding_minutes: 0,
              api_token: 'aToken',
              at: '2018-09-01T08:21:24+00:00',
              ical_enabled: true,
            },
          ],
          duration_format: 'improved',
          obm: {
            included: false,
            nr: 0,
            actions: 'tree',
          },
        },
      },
    },
  },
  workspaces: {
    apiFetchClockifyWorkspaces: {
      url: '/clockify/api/workspaces/',
      method: 'GET',
      response: [
        {
          id: 'testWorkspaceA',
          name: 'Testing',
          hourlyRate: {
            amount: 0,
            currency: 'USD',
          },
          memberships: [
            {
              userId: 'testUser',
              hourlyRate: null as any,
              membershipType: 'WORKSPACE',
              membershipStatus: 'ACTIVE',
              target: 'membershipTarget',
            },
          ],
          workspaceSettings: {
            timeRoundingInReports: false,
            onlyAdminsSeeBillableRates: true,
            onlyAdminsCreateProject: true,
            onlyAdminsSeeDashboard: false,
            defaultBillableProjects: true,
            lockTimeEntries: null as any,
            round: {
              round: 'Round to nearest',
              minutes: '15',
            },
            projectFavorites: true,
            canSeeTimeSheet: false,
            projectPickerSpecialFilter: false,
            forceProjects: false,
            forceTasks: false,
            forceTags: false,
            forceDescription: false,
            onlyAdminsSeeAllTimeEntries: false,
            onlyAdminsSeePublicProjectsEntries: false,
            trackTimeDownToSecond: true,
            projectGroupingLabel: 'client',
          },
          imageUrl: '',
        },
      ],
    },
    apiFetchTogglWorkspaces: {
      url: '/toggl/api/workspaces',
      method: 'GET',
      response: [
        {
          id: 200001,
          name: 'Workspace A',
          profile: 0,
          premium: false,
          admin: true,
          default_hourly_rate: 0,
          default_currency: 'USD',
          only_admins_may_create_projects: false,
          only_admins_see_billable_rates: false,
          only_admins_see_team_dashboard: false,
          projects_billable_by_default: false,
          rounding: 0,
          rounding_minutes: 0,
          api_token: 'aToken',
          at: '2018-11-13T02:36:04+00:00',
          ical_enabled: true,
        },
        {
          id: 200002,
          name: 'Workspace B',
          profile: 0,
          premium: false,
          admin: true,
          default_hourly_rate: 0,
          default_currency: 'USD',
          only_admins_may_create_projects: false,
          only_admins_see_billable_rates: false,
          only_admins_see_team_dashboard: false,
          projects_billable_by_default: true,
          rounding: 0,
          rounding_minutes: 0,
          api_token: 'bToken',
          at: '2017-06-29T14:48:42+00:00',
          ical_enabled: true,
        },
      ],
    },
  },
};

export default responses as any;
