// @ts-ignore
const responses = {
  clients: {
    apiFetchClockifyClients: {
      url: '/clockify/api/workspaces/{workspaceId}/clients/',
      method: 'GET',
      response: [
        {
          id: 'testClientA',
          name: 'Test Client A',
          workspaceId: 'testWorkspaceA',
        },
        {
          id: 'testClientB',
          name: 'Test Client B',
          workspaceId: 'testWorkspaceA',
        },
      ],
    },
    apiFetchTogglClients: {
      url: '/toggl/api/workspaces/1738517/clients',
      method: 'GET',
      response: [
        {
          id: 37389358,
          wid: 1738517,
          name: 'Client A',
          at: '2018-02-18T16:54:02+00:00',
        },
        {
          id: 19521509,
          wid: 1738517,
          name: 'Client B',
          at: '2016-12-06T03:48:38+00:00',
        },
        {
          id: 21773956,
          wid: 1738517,
          name: 'Client C',
          at: '2017-04-26T14:18:07+00:00',
        },
      ],
    },
  },
  projects: {
    apiFetchClockifyProjects: {
      url: '/clockify/api/workspaces/{workspaceId}/projects/',
      method: 'GET',
      response: [
        {
          id: 'testProjectA',
          name: 'Project One',
          hourlyRate: null as any,
          clientId: '',
          client: null as any,
          workspaceId: 'testWorkspaceA',
          billable: true,
          memberships: [
            {
              userId: 'userId',
              hourlyRate: null as any,
              membershipType: 'PROJECT',
              membershipStatus: 'ACTIVE',
              target: 'targetA',
            },
          ],
          color: '#f44336',
          estimate: {
            estimate: 'PT0S',
            type: 'AUTO',
          },
          archived: false,
          tasks: [] as any,
          public: false,
        },
        {
          id: 'testProjectB',
          name: 'Project Two',
          hourlyRate: null,
          clientId: '',
          client: null,
          workspaceId: 'testWorkspaceA',
          billable: true,
          memberships: [
            {
              userId: 'userId',
              hourlyRate: null,
              membershipType: 'PROJECT',
              membershipStatus: 'ACTIVE',
              target: 'targetB',
            },
          ],
          color: '#9ba8b0',
          estimate: {
            estimate: 'PT0S',
            type: 'AUTO',
          },
          archived: false,
          tasks: [],
          public: false,
        },
      ],
    },
    apiFetchTogglProjects: {
      url: '/toggl/api/workspaces/1738517/projects',
      method: 'GET',
      response: [
        {
          id: 100755951,
          wid: 1738517,
          cid: 37389358,
          name: 'Test Project A',
          billable: false,
          is_private: true,
          active: true,
          template: false,
          at: '2018-02-18T16:54:05+00:00',
          created_at: '2018-02-18T16:54:05+00:00',
          color: '11',
          auto_estimates: false,
          actual_hours: 360,
          hex_color: '#205500',
        },
        {
          id: 38219065,
          wid: 1738517,
          cid: 21773956,
          name: 'Test Project B',
          billable: false,
          is_private: true,
          active: true,
          template: false,
          at: '2017-06-10T04:25:45+00:00',
          created_at: '2017-04-26T14:18:29+00:00',
          color: '3',
          auto_estimates: false,
          actual_hours: 35,
          hex_color: '#fb8b14',
        },
        {
          id: 91788263,
          wid: 1738517,
          cid: 21773956,
          name: 'Test Project C',
          billable: false,
          is_private: true,
          active: true,
          template: false,
          at: '2018-01-04T18:18:13+00:00',
          created_at: '2018-01-04T18:18:06+00:00',
          color: '8',
          auto_estimates: false,
          actual_hours: 46,
          hex_color: '#3750b5',
        },
      ],
    },
  },
  tags: {
    apiFetchClockifyTags: {
      url: '/clockify/api/workspaces/{workspaceId}/tags/',
      method: 'GET',
      response: [
        {
          id: 'testTagA',
          name: 'Tag One',
          workspaceId: 'testWorkspaceA',
        },
        {
          id: 'testTagB',
          name: 'Tag Two',
          workspaceId: 'testWorkspaceA',
        },
      ],
    },
    apiFetchTogglTags: {
      url: '/toggl/api/workspaces/1738517/tags',
      method: 'GET',
      response: [
        {
          id: 3405850,
          wid: 1738517,
          name: 'tag-a',
          at: '2017-07-16T16:47:11+00:00',
        },
        {
          id: 3250640,
          wid: 1738517,
          name: 'tag-b',
          at: '2017-05-20T17:58:26+00:00',
        },
        {
          id: 3250642,
          wid: 1738517,
          name: 'tag-c',
          at: '2017-05-20T17:59:51+00:00',
        },
      ],
    },
  },
  tasks: {
    apiFetchClockifyTasks: {
      url: '/clockify/api/workspaces/{workspaceId}/tasks/',
      method: 'GET',
      response: [
        {
          id: 'testTaskA',
          name: 'Test Task A',
          projectId: 'testProjectA',
          assigneeId: 'userId',
          estimate: 'PT30M',
          status: 'ACTIVE',
        },
        {
          id: 'testTaskB',
          name: 'Test Task A',
          projectId: 'testProjectA',
          assigneeId: 'userId',
          estimate: 'PT120H',
          status: 'ACTIVE',
        },
      ],
    },
    apiFetchTogglTasks: {
      url: '/toggl/api/workspaces/1738517/tasks',
      method: 'GET',
      response: [
        {
          name: 'Test Task A',
          id: 585880444,
          wid: 1738517,
          pid: 100755951,
          uid: 4456652,
          active: true,
          at: '2013-03-06T09:15:51+00:00',
          estimated_seconds: 7200,
        },
        {
          name: 'Test Task B',
          id: 585881000,
          wid: 1738517,
          pid: 100755951,
          uid: 2540893,
          active: true,
          at: '2013-03-06T09:15:59+00:00',
          estimated_seconds: 0,
        },
      ],
    },
  },
  timeEntries: {
    apiFetchClockifyTimeEntries: {
      url:
        '/clockify/api/workspaces/{workspaceId}/timeEntries/user/{userId}/entriesInRange',
      body: {
        start: '2018-01-01T00:00:00.000Z',
        end: '2018-12-31T23:59:59.999Z',
      },
      method: 'POST',
      response: [
        {
          id: 'testTimeEntryA',
          description: 'Description of time entry A.',
          tags: null as any,
          user: {
            id: 'userId',
            email: 'test@test.com',
            name: 'John User',
            memberships: [
              {
                userId: 'userId',
                hourlyRate: null as any,
                membershipType: 'WORKSPACE',
                membershipStatus: 'ACTIVE',
                target: 'targetA',
              },
            ],
            profilePicture:
              'https://s3.eu-central-1.amazonaws.com/clockify/no-user-image.png',
            activeWorkspace: 'testWorkspaceA',
            defaultWorkspace: 'testWorkspaceA',
            settings: {
              weekStart: 'MONDAY',
              timeZone: 'America/Chicago',
              timeFormat: 'HOUR12',
              dateFormat: 'MM/DD/YYYY',
              sendNewsletter: true,
              weeklyUpdates: true,
              longRunning: false,
              summaryReportSettings: {
                group: 'Project',
                subgroup: 'Time Entry',
              },
              isCompactViewOn: false,
              dashboardSelection: 'ME',
              timeTrackingManual: false,
            },
            status: 'ACTIVE',
          },
          billable: false,
          task: {
            id: 'testTaskA',
            name: 'Test Task A',
            projectId: 'testProjectA',
            assigneeId: 'userId',
            estimate: 'PT30M',
            status: 'ACTIVE',
          },
          project: {
            id: 'testProjectA',
            name: 'Test Project A',
            hourlyRate: null as any,
            clientId: 'testClientA',
            workspaceId: 'testWorkspaceA',
            billable: false,
            memberships: [
              {
                userId: 'userId',
                hourlyRate: null as any,
                membershipType: 'PROJECT',
                membershipStatus: 'ACTIVE',
                target: 'testTargetA',
              },
            ],
            color: '#03a9f4',
            estimate: {
              estimate: 'PT1168H30M',
              type: 'AUTO',
            },
            archived: false,
            duration: 'PT288H5M',
            clientName: 'Test Client A',
            public: false,
          },
          timeInterval: {
            start: '2018-10-09T21:00:00Z',
            end: '2018-10-09T21:30:00Z',
            duration: 'PT30M',
          },
          workspaceId: 'testWorkspaceA',
          totalBillable: null as any,
          hourlyRate: null as any,
          isLocked: false,
          projectId: 'testProjectA',
        },
        {
          id: 'testTimeEntryB',
          description: 'Description of time entry B.',
          tags: null,
          user: {
            id: 'userId',
            email: 'test@test.com',
            name: 'John User',
            memberships: [
              {
                userId: 'userId',
                hourlyRate: null as any,
                membershipType: 'WORKSPACE',
                membershipStatus: 'ACTIVE',
                target: 'targetA',
              },
            ],
            profilePicture:
              'https://s3.eu-central-1.amazonaws.com/clockify/no-user-image.png',
            activeWorkspace: 'testWorkspaceA',
            defaultWorkspace: 'testWorkspaceA',
            settings: {
              weekStart: 'MONDAY',
              timeZone: 'America/Chicago',
              timeFormat: 'HOUR12',
              dateFormat: 'MM/DD/YYYY',
              sendNewsletter: true,
              weeklyUpdates: true,
              longRunning: false,
              summaryReportSettings: {
                group: 'Project',
                subgroup: 'Time Entry',
              },
              isCompactViewOn: false,
              dashboardSelection: 'ME',
              timeTrackingManual: false,
            },
            status: 'ACTIVE',
          },
          billable: false,
          task: {
            id: 'testTaskA',
            name: 'Test Task A',
            projectId: 'testProjectA',
            assigneeId: 'userId',
            estimate: 'PT30M',
            status: 'ACTIVE',
          },
          project: {
            id: 'testProjectA',
            name: 'Test Project A',
            hourlyRate: null as any,
            clientId: 'testClientA',
            workspaceId: 'testWorkspaceA',
            billable: false,
            memberships: [
              {
                userId: 'userId',
                hourlyRate: null as any,
                membershipType: 'PROJECT',
                membershipStatus: 'ACTIVE',
                target: 'testTargetA',
              },
            ],
            color: '#03a9f4',
            estimate: {
              estimate: 'PT1168H30M',
              type: 'AUTO',
            },
            archived: false,
            duration: 'PT288H5M',
            clientName: 'Test Client A',
            public: false,
          },
          timeInterval: {
            start: '2018-10-09T21:00:00Z',
            end: '2018-10-09T21:30:00Z',
            duration: 'PT30M',
          },
          workspaceId: 'testWorkspaceA',
          totalBillable: null as any,
          hourlyRate: null as any,
          isLocked: false,
          projectId: 'testProjectA',
        },
      ],
    },
    apiFetchTogglTimeEntries: {
      url:
        '/toggl/reports/details?workspace_id=1738517&since=2018-01-01&until=2018-12-31&user_agent=test@test.com',
      method: 'GET',
      response: {
        total_grand: 2985300000,
        total_billable: null as any,
        total_currencies: [
          {
            currency: null as any,
            amount: null as any,
          },
        ],
        total_count: 300,
        per_page: 50,
        data: [
          {
            id: 585878424,
            pid: 38219065,
            tid: 585880444,
            uid: 2540893,
            description: 'Continued working on tests for something.',
            start: '2018-01-01T11:00:00-06:00',
            end: '2018-01-01T17:15:00-06:00',
            updated: '2018-05-21T13:53:05-05:00',
            dur: 22500000,
            user: 'John Test',
            use_stop: true,
            client: 'Client C',
            project: 'Test Project B',
            project_color: '0',
            project_hex_color: '#fb8b14',
            task: 'Test Task A',
            billable: null as any,
            is_billable: false,
            cur: null as any,
            tags: ['tag-a'],
          },
          {
            id: 585881000,
            pid: 38219065,
            tid: 585880444,
            uid: 2540893,
            description: 'Work on some other test related thing.',
            start: '2018-02-03T18:35:00-06:00',
            end: '2018-02-03T19:00:00-06:00',
            updated: '2018-04-26T09:52:00-05:00',
            dur: 1500000,
            user: 'John Test',
            use_stop: true,
            client: 'Client C',
            project: 'Test Project B',
            project_color: '0',
            project_hex_color: '#fb8b14',
            task: 'Test Task A',
            billable: null as any,
            is_billable: false,
            cur: null as any,
            tags: ['tag-a', 'tag-b'],
          },
          {
            id: 585881403,
            pid: 38219065,
            tid: 585880444,
            uid: 2540893,
            description: 'Keep on choogling with tests.',
            start: '2018-02-03T19:05:00-06:00',
            end: '2018-02-03T19:30:00-06:00',
            updated: '2018-04-26T09:52:01-05:00',
            dur: 1500000,
            user: 'John Test',
            use_stop: true,
            client: 'Client C',
            project: 'Test Project B',
            project_color: '0',
            project_hex_color: '#fb8b14',
            task: 'Test Task A',
            billable: null as any,
            is_billable: false,
            cur: null as any,
            tags: [],
          },
          {
            id: 765593610,
            pid: 91788263,
            tid: null,
            uid: 2540893,
            description: 'Continue working on thing.',
            start: '2018-05-03T09:30:47-06:00',
            end: '2018-05-03T12:00:47-06:00',
            updated: '2018-01-04T12:18:58-06:00',
            dur: 9000000,
            user: 'John Test',
            use_stop: true,
            client: 'Client C',
            project: 'Test Project C',
            project_color: '0',
            project_hex_color: '#3750b5',
            task: null as any,
            billable: null as any,
            is_billable: false,
            cur: null as any,
            tags: ['tag-c'],
          },
          {
            id: 765594088,
            pid: 91788263,
            tid: null as any,
            uid: 2540893,
            description: 'Work on other thing some more.',
            start: '2018-05-04T10:00:25-06:00',
            end: '2018-05-04T12:20:25-06:00',
            updated: '2018-01-04T12:19:36-06:00',
            dur: 8400000,
            user: 'John Test',
            use_stop: true,
            client: 'Client C',
            project: 'Test Project C',
            project_color: '0',
            project_hex_color: '#3750b5',
            task: null as any,
            billable: null as any,
            is_billable: false,
            cur: null as any,
            tags: ['tag-c'],
          },
          {
            id: 768127151,
            pid: 91788263,
            tid: null as any,
            uid: 2540893,
            description: 'Spend time doing a thing.',
            start: '2018-06-08T17:00:00-06:00',
            end: '2018-06-08T23:00:00-06:00',
            updated: '2018-01-08T22:58:20-06:00',
            dur: 21600000,
            user: 'John Test',
            use_stop: true,
            client: 'Client C',
            project: 'Test Project C',
            project_color: '0',
            project_hex_color: '#3750b5',
            task: null as any,
            billable: null as any,
            is_billable: false,
            cur: null as any,
            tags: [],
          },
          {
            id: 951503092,
            pid: 100755951,
            tid: null as any,
            uid: 2540893,
            description: 'Continue working on the thing I mentioned.',
            start: '2018-08-14T09:30:33-05:00',
            end: '2018-08-14T12:00:33-05:00',
            updated: '2018-08-17T17:09:50-05:00',
            dur: 9000000,
            user: 'John Test',
            use_stop: true,
            client: 'Client A',
            project: 'Test Project A',
            project_color: '0',
            project_hex_color: '#205500',
            task: null as any,
            billable: null as any,
            is_billable: false,
            cur: null as any,
            tags: ['tag-a', 'tag-c'],
          },
          {
            id: 958462738,
            pid: 100755951,
            tid: null as any,
            uid: 2540893,
            description: 'This thing sure is taking a while.',
            start: '2018-08-25T10:00:06-05:00',
            end: '2018-08-25T12:00:06-05:00',
            updated: '2018-08-27T13:54:19-05:00',
            dur: 7200000,
            user: 'John Test',
            use_stop: true,
            client: 'Client A',
            project: 'Test Project A',
            project_color: '0',
            project_hex_color: '#205500',
            task: null as any,
            billable: null as any,
            is_billable: false,
            cur: null as any,
            tags: [],
          },
          {
            id: 961957245,
            pid: 100755951,
            tid: null as any,
            uid: 2540893,
            description: 'Finally finish the thing.',
            start: '2018-08-28T18:00:08-05:00',
            end: '2018-08-28T23:00:08-05:00',
            updated: '2018-08-30T15:52:21-05:00',
            dur: 18000000,
            user: 'John Test',
            use_stop: true,
            client: 'Client A',
            project: 'Test Project A',
            project_color: '0',
            project_hex_color: '#205500',
            task: null as any,
            billable: null as any,
            is_billable: false,
            cur: null as any,
            tags: ['tag-b'],
          },
          {
            id: 970210589,
            pid: 100755951,
            tid: null as any,
            uid: 2540893,
            description: 'Restart thing because the thing is dumb.',
            start: '2018-09-09T12:00:00-05:00',
            end: '2018-09-09T14:00:00-05:00',
            updated: '2018-09-10T13:06:56-05:00',
            dur: 7200000,
            user: 'John Test',
            use_stop: true,
            client: 'Client A',
            project: 'Test Project A',
            project_color: '0',
            project_hex_color: '#205500',
            task: null as any,
            billable: null as any,
            is_billable: false,
            cur: null as any,
            tags: [],
          },
        ],
      },
    },
  },
  users: {
    apiFetchClockifyUserDetails: {
      url: '/clockify/api/users/{userId}',
      method: 'GET',
      response: {
        id: 'userId',
        email: 'test@test.com',
        name: 'Testing',
        memberships: [
          {
            userId: 'userId',
            hourlyRate: null as any,
            membershipType: 'WORKSPACE',
            membershipStatus: 'ACTIVE',
            target: 'targetId',
          },
        ],
        profilePicture:
          'https://s3.eu-central-1.amazonaws.com/clockify/no-user-image.png',
        activeWorkspace: 'testWorkspaceA',
        defaultWorkspace: 'testWorkspaceA',
        settings: {
          weekStart: 'MONDAY',
          timeZone: 'America/Chicago',
          timeFormat: 'HOUR12',
          dateFormat: 'MM/DD/YYYY',
          sendNewsletter: true,
          weeklyUpdates: false,
          longRunning: false,
          summaryReportSettings: {
            group: 'Project',
            subgroup: 'Time Entry',
          },
          isCompactViewOn: false,
          dashboardSelection: 'ME',
          timeTrackingManual: false,
        },
        status: 'ACTIVE',
      },
    },
    apiFetchTogglUserDetails: {
      url: '/toggl/api/me',
      method: 'GET',
      response: {
        since: 1545596501,
        data: {
          id: 100001,
          api_token: 'abcdefg12344567dskfj23432',
          default_wid: 200001,
          email: 'test@test.com',
          fullname: 'John User',
          jquery_timeofday_format: 'h:i A',
          jquery_date_format: 'm/d/Y',
          timeofday_format: 'h:mm A',
          date_format: 'MM/DD/YYYY',
          store_start_and_stop_time: false,
          beginning_of_week: 0,
          language: 'en_US',
          image_url: 'https://user.url',
          sidebar_piechart: true,
          at: '2017-09-10T21:02:53+00:00',
          created_at: '2016-11-01T18:05:24+00:00',
          retention: 9,
          record_timeline: true,
          render_timeline: true,
          timeline_enabled: true,
          timeline_experiment: false,
          new_blog_post: {},
          should_upgrade: true,
          achievements_enabled: true,
          timezone: 'America/Chicago',
          openid_enabled: true,
          openid_email: 'test@test.com',
          send_product_emails: false,
          send_weekly_report: false,
          send_timer_notifications: false,
          last_blog_entry: '',
          invitation: {},
          workspaces: [
            {
              id: 1738517,
              name: 'Test Workspace',
              profile: 0,
              premium: false,
              admin: true,
              default_hourly_rate: 0,
              default_currency: 'USD',
              only_admins_may_create_projects: false,
              only_admins_see_billable_rates: false,
              only_admins_see_team_dashboard: false,
              projects_billable_by_default: false,
              rounding: 0,
              rounding_minutes: 0,
              api_token: 'abcdefg12344567dskfj23432',
              at: '2018-11-13T02:36:04+00:00',
              ical_enabled: true,
            },
          ],
          duration_format: 'improved',
          obm: {
            included: false,
            nr: 0,
            actions: 'tree',
          },
        },
      },
    },
    apiFetchClockifyUsersInProject: {
      url: '/',
      method: 'GET',
      response: [] as any,
    },
    apiFetchTogglUsersInProject: {
      url: '/toggl/api/projects/100755951/project_users',
      method: 'GET',
      response: [
        {
          id: 65027773,
          pid: 100755951,
          uid: 4456652,
          wid: 1738517,
          manager: false,
          rate: null as any,
          at: '2018-11-13T02:08:21+00:00',
        },
        {
          id: 61708305,
          pid: 100755951,
          uid: 2540893,
          wid: 1738517,
          manager: true,
          rate: null as any,
          at: '2018-08-23T19:20:58+00:00',
        },
      ],
    },
    apiFetchClockifyUsersInWorkspace: {
      url: '/clockify/api/workspaces/${workspaceId}/users/',
      method: 'GET',
      response: [] as any,
    },
    apiFetchTogglUsersInWorkspace: {
      url: '/toggl/api/workspaces/1738517/users',
      method: 'GET',
      response: [
        {
          id: 4456652,
          email: 'otherUser@test.com',
          fullname: 'Betsy Testerossa',
          jquery_timeofday_format: 'h:i A',
          jquery_date_format: 'm/d/Y',
          timeofday_format: 'h:mm A',
          date_format: 'MM/DD/YYYY',
          store_start_and_stop_time: true,
          beginning_of_week: 1,
          language: 'en_US',
          image_url: 'https://assets.toggl.com/images/profile.png',
          sidebar_piechart: true,
          at: '2018-11-13T02:07:42+00:00',
          created_at: '2018-11-13T02:05:32+00:00',
          retention: 9,
          record_timeline: false,
          render_timeline: false,
          timeline_enabled: false,
          timeline_experiment: false,
          new_blog_post: {},
          should_upgrade: true,
          achievements_enabled: false,
          timezone: 'America/Chicago',
          openid_enabled: false,
          send_product_emails: true,
          send_weekly_report: true,
          send_timer_notifications: true,
          last_blog_entry: '',
          invitation: {},
          duration_format: 'improved',
          obm: {
            included: false,
            nr: 0,
            actions: 'tree',
          },
        },
        {
          id: 2540893,
          default_wid: 1738517,
          email: 'test@test.com',
          fullname: 'John Test',
          jquery_timeofday_format: 'h:i A',
          jquery_date_format: 'm/d/Y',
          timeofday_format: 'h:mm A',
          date_format: 'MM/DD/YYYY',
          store_start_and_stop_time: false,
          beginning_of_week: 0,
          language: 'en_US',
          image_url: 'https://user.url',
          sidebar_piechart: true,
          at: '2017-09-10T21:02:53+00:00',
          created_at: '2016-11-01T18:05:24+00:00',
          retention: 9,
          record_timeline: true,
          render_timeline: true,
          timeline_enabled: true,
          timeline_experiment: false,
          new_blog_post: {},
          should_upgrade: true,
          achievements_enabled: false,
          timezone: 'America/Chicago',
          openid_enabled: true,
          openid_email: 'test@test.com',
          send_product_emails: false,
          send_weekly_report: true,
          send_timer_notifications: false,
          last_blog_entry: '',
          invitation: {},
          duration_format: 'improved',
          obm: {
            included: false,
            nr: 0,
            actions: 'tree',
          },
        },
      ],
    },
  },
  workspaces: {
    apiFetchClockifyWorkspaces: {
      url: '/clockify/api/workspaces/',
      method: 'GET',
      response: [
        {
          id: 'testWorkspaceA',
          name: 'Testing',
          hourlyRate: {
            amount: 0,
            currency: 'USD',
          },
          memberships: [
            {
              userId: 'testUser',
              hourlyRate: null as any,
              membershipType: 'WORKSPACE',
              membershipStatus: 'ACTIVE',
              target: 'membershipTarget',
            },
          ],
          workspaceSettings: {
            timeRoundingInReports: false,
            onlyAdminsSeeBillableRates: true,
            onlyAdminsCreateProject: true,
            onlyAdminsSeeDashboard: false,
            defaultBillableProjects: true,
            lockTimeEntries: null as any,
            round: {
              round: 'Round to nearest',
              minutes: '15',
            },
            projectFavorites: true,
            canSeeTimeSheet: false,
            projectPickerSpecialFilter: false,
            forceProjects: false,
            forceTasks: false,
            forceTags: false,
            forceDescription: false,
            onlyAdminsSeeAllTimeEntries: false,
            onlyAdminsSeePublicProjectsEntries: false,
            trackTimeDownToSecond: true,
            projectGroupingLabel: 'client',
          },
          imageUrl: '',
        },
      ],
    },
    apiFetchTogglWorkspaces: {
      url: '/toggl/api/workspaces',
      method: 'GET',
      response: [
        {
          id: 1738517,
          name: 'Test Workspace',
          profile: 0,
          premium: false,
          admin: true,
          default_hourly_rate: 0,
          default_currency: 'USD',
          only_admins_may_create_projects: false,
          only_admins_see_billable_rates: false,
          only_admins_see_team_dashboard: false,
          projects_billable_by_default: false,
          rounding: 0,
          rounding_minutes: 0,
          api_token: 'abcdefg12344567dskfj23432',
          at: '2018-11-13T02:36:04+00:00',
          ical_enabled: true,
        },
      ],
    },
  },
};

export default responses as any;
